-- ═══════════════════════════════════════════════════════════════════════════
-- 034_tema_suku — 24 tema undangan per SUKU / budaya daerah yang belum punya
-- tema sendiri (Gayo, Nias, Karo, Mandailing, Mentawai, Melayu Deli, Lampung
-- Pesisir, Osing, Madura, Pekalongan, Lurik, Baduy, Bali Aga, Bima, Manggarai,
-- Timor, Iban, Kutai, Makassar, Bugis Bone, Sangihe, Kei, Biak, Sentani).
-- DIBANGKITKAN scripts/provinsi/build.py . suku — jangan disunting tangan.
--
-- Aset: public/img/tema/suku/. Idempoten: ON CONFLICT DO NOTHING; ornamen
-- hanya diisi untuk tema yang belum punya ornamen. Rupa (bentuk tiap bagian)
-- diisi 035_rupa_suku.sql. WAJIB setelah 031 & 033.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── Animasi buka khas suku ──
INSERT INTO animations (kind, slug, name, spec, css, builtin, sort_order) VALUES ('buka', 'suku-kerawang-gayo', 'Pintu Kerawang Gayo', '{"split": "tb", "move_pct": 105, "rotate": 0, "scale": 108, "fade": true, "duration_ms": 1400, "delay_ms": 200, "easing": "lembut", "content_exit": "naik", "orn_effect": "jatuh", "orn_size": 110, "fill": "image", "border": true, "panel_image": "/img/tema/suku/anim/pintu-kerawang-gayo.svg", "orn_image": "/img/tema/suku/anim/lambang-kerawang-gayo.svg"}'::jsonb, '', FALSE, 130) ON CONFLICT (kind, slug) DO NOTHING;
INSERT INTO animations (kind, slug, name, spec, css, builtin, sort_order) VALUES ('buka', 'suku-omo-sebua-nias', 'Pintu Omo Sebua Nias', '{"split": "lr", "move_pct": 0, "rotate": 105, "scale": 100, "fade": false, "duration_ms": 1500, "delay_ms": 300, "easing": "tegas", "content_exit": "pudar", "orn_effect": "membesar", "orn_size": 120, "fill": "image", "border": true, "panel_image": "/img/tema/suku/anim/pintu-omo-sebua-nias.svg", "orn_image": "/img/tema/suku/anim/lambang-omo-sebua-nias.svg"}'::jsonb, '', FALSE, 131) ON CONFLICT (kind, slug) DO NOTHING;
INSERT INTO animations (kind, slug, name, spec, css, builtin, sort_order) VALUES ('buka', 'suku-siwaluh-jabu-karo', 'Pintu Siwaluh Jabu Karo', '{"split": "full", "move_pct": 0, "rotate": 0, "scale": 130, "fade": true, "duration_ms": 1300, "delay_ms": 250, "easing": "lembut", "content_exit": "membesar", "orn_effect": "membesar", "orn_size": 120, "fill": "image", "border": true, "panel_image": "/img/tema/suku/anim/pintu-siwaluh-jabu-karo.svg", "orn_image": "/img/tema/suku/anim/lambang-siwaluh-jabu-karo.svg"}'::jsonb, '', FALSE, 132) ON CONFLICT (kind, slug) DO NOTHING;
INSERT INTO animations (kind, slug, name, spec, css, builtin, sort_order) VALUES ('buka', 'suku-istana-maimun-deli', 'Pintu Istana Maimun Deli', '{"split": "lr", "move_pct": 104, "rotate": 0, "scale": 100, "fade": false, "duration_ms": 1300, "delay_ms": 250, "easing": "lembut", "content_exit": "naik", "orn_effect": "berputar", "orn_size": 100, "fill": "image", "border": true, "panel_image": "/img/tema/suku/anim/pintu-istana-maimun-deli.svg", "orn_image": "/img/tema/suku/anim/lambang-istana-maimun-deli.svg"}'::jsonb, '', FALSE, 135) ON CONFLICT (kind, slug) DO NOTHING;
INSERT INTO animations (kind, slug, name, spec, css, builtin, sort_order) VALUES ('buka', 'suku-tapis-saibatin', 'Pintu Tapis Saibatin Pesisir', '{"split": "tb", "move_pct": 103, "rotate": 0, "scale": 100, "fade": false, "duration_ms": 1300, "delay_ms": 250, "easing": "tegas", "content_exit": "mengecil", "orn_effect": "membesar", "orn_size": 120, "fill": "image", "border": true, "panel_image": "/img/tema/suku/anim/pintu-tapis-saibatin.svg", "orn_image": "/img/tema/suku/anim/lambang-tapis-saibatin.svg"}'::jsonb, '', FALSE, 136) ON CONFLICT (kind, slug) DO NOTHING;
INSERT INTO animations (kind, slug, name, spec, css, builtin, sort_order) VALUES ('buka', 'suku-gandrung-osing', 'Pintu Gandrung Osing Banyuwangi', '{"split": "full", "move_pct": 105, "rotate": 0, "scale": 100, "fade": false, "duration_ms": 1400, "delay_ms": 200, "easing": "lembut", "content_exit": "naik", "orn_effect": "jatuh", "orn_size": 100, "fill": "image", "border": true, "panel_image": "/img/tema/suku/anim/pintu-gandrung-osing.svg", "orn_image": "/img/tema/suku/anim/lambang-gandrung-osing.svg"}'::jsonb, '', FALSE, 137) ON CONFLICT (kind, slug) DO NOTHING;
INSERT INTO animations (kind, slug, name, spec, css, builtin, sort_order) VALUES ('buka', 'suku-songke-manggarai', 'Pintu Songke Manggarai', '{"split": "tb", "move_pct": 105, "rotate": 0, "scale": 108, "fade": true, "duration_ms": 1400, "delay_ms": 200, "easing": "lembut", "content_exit": "naik", "orn_effect": "jatuh", "orn_size": 110, "fill": "image", "border": true, "panel_image": "/img/tema/suku/anim/pintu-songke-manggarai.svg", "orn_image": "/img/tema/suku/anim/lambang-songke-manggarai.svg"}'::jsonb, '', FALSE, 144) ON CONFLICT (kind, slug) DO NOTHING;
INSERT INTO animations (kind, slug, name, spec, css, builtin, sort_order) VALUES ('buka', 'suku-pua-kumbu-iban', 'Pintu Pua Kumbu Iban', '{"split": "lr", "move_pct": 0, "rotate": 105, "scale": 100, "fade": false, "duration_ms": 1500, "delay_ms": 300, "easing": "tegas", "content_exit": "pudar", "orn_effect": "membesar", "orn_size": 120, "fill": "image", "border": true, "panel_image": "/img/tema/suku/anim/pintu-pua-kumbu-iban.svg", "orn_image": "/img/tema/suku/anim/lambang-pua-kumbu-iban.svg"}'::jsonb, '', FALSE, 146) ON CONFLICT (kind, slug) DO NOTHING;
INSERT INTO animations (kind, slug, name, spec, css, builtin, sort_order) VALUES ('buka', 'suku-baju-bodo-makassar', 'Pintu Baju Bodo Makassar', '{"split": "full", "move_pct": 0, "rotate": 0, "scale": 130, "fade": true, "duration_ms": 1300, "delay_ms": 250, "easing": "lembut", "content_exit": "membesar", "orn_effect": "membesar", "orn_size": 120, "fill": "image", "border": true, "panel_image": "/img/tema/suku/anim/pintu-baju-bodo-makassar.svg", "orn_image": "/img/tema/suku/anim/lambang-baju-bodo-makassar.svg"}'::jsonb, '', FALSE, 148) ON CONFLICT (kind, slug) DO NOTHING;
INSERT INTO animations (kind, slug, name, spec, css, builtin, sort_order) VALUES ('buka', 'suku-ain-ni-ain-kei', 'Pintu Ain ni Ain Kei', '{"split": "lr", "move_pct": 104, "rotate": 0, "scale": 100, "fade": false, "duration_ms": 1300, "delay_ms": 250, "easing": "lembut", "content_exit": "naik", "orn_effect": "berputar", "orn_size": 100, "fill": "image", "border": true, "panel_image": "/img/tema/suku/anim/pintu-ain-ni-ain-kei.svg", "orn_image": "/img/tema/suku/anim/lambang-ain-ni-ain-kei.svg"}'::jsonb, '', FALSE, 151) ON CONFLICT (kind, slug) DO NOTHING;
INSERT INTO animations (kind, slug, name, spec, css, builtin, sort_order) VALUES ('buka', 'suku-wor-biak', 'Pintu Wor Biak', '{"split": "tb", "move_pct": 103, "rotate": 0, "scale": 100, "fade": false, "duration_ms": 1300, "delay_ms": 250, "easing": "tegas", "content_exit": "mengecil", "orn_effect": "membesar", "orn_size": 120, "fill": "image", "border": true, "panel_image": "/img/tema/suku/anim/pintu-wor-biak.svg", "orn_image": "/img/tema/suku/anim/lambang-wor-biak.svg"}'::jsonb, '', FALSE, 153) ON CONFLICT (kind, slug) DO NOTHING;

-- ── Tema ──
-- Aceh Tengah — Gayo: Kerawang Gayo
INSERT INTO themes (slug, name, category, nuansa, palette, region, description, tags, badge, layout, ornament, font, tokens, dark, sort_order, script_font, bg_image, frame_image, card_deco, float_deco, open_anim, page_mode, scroll_anim, image_url, image_mode, gerak_judul, gerak_foto, ken_burns, listed)
VALUES ('kerawang-gayo', 'Kerawang Gayo', 'Luxury', 'Aceh', 'gold', 'Aceh Tengah — Gayo', 'Kain kerawang Gayo berwarna merah-kuning-hijau di atas hitam, kopi dataran tinggi, dan umah pitu ruang di tepi Danau Laut Tawar.', '["Mode Gelap", "Kerawang", "Dataran Tinggi", "Provinsi Aceh Tengah — Gayo"]'::jsonb, 'Baru', 'klasik', 'none', 'marcellus', '{"bg": "#120f0c", "card": "#23201d", "primary": "#e4b740", "on-primary": "#0e0c0a", "gold": "#e4b740", "gold-deep": "#e4b740", "ink": "#f8edcf", "muted": "#9c9481"}'::jsonb, TRUE, 400, 'allura', '/img/tema/suku/kerawang-gayo-latar.svg', '/img/tema/suku/kerawang-gayo-bingkai.svg', '/img/tema/suku/kerawang-gayo-hiasan.svg', 'kilau-emas', 'suku-kerawang-gayo', 'satu', 'tenun', '/img/tema/suku/kerawang-gayo-motif.svg', 'pola', 'zoom-masuk', 'zoom-masuk', TRUE, TRUE)
ON CONFLICT (slug) DO NOTHING;
-- Nias — Sumatera Utara: Omo Sebua Nias
INSERT INTO themes (slug, name, category, nuansa, palette, region, description, tags, badge, layout, ornament, font, tokens, dark, sort_order, script_font, bg_image, frame_image, card_deco, float_deco, open_anim, page_mode, scroll_anim, image_url, image_mode, gerak_judul, gerak_foto, ken_burns, listed)
VALUES ('omo-sebua-nias', 'Omo Sebua Nias', 'Adat', 'Nias', 'terra', 'Nias — Sumatera Utara', 'Rumah adat omo sebua berkaki kayu raksasa, batu hombo yang dilompati para pemuda, dan warna merah-kuning-hitam bangsawan Nias.', '["Hombo Batu", "Merah Kuning", "Rumah Panggung", "Provinsi Nias — Sumatera Utara"]'::jsonb, 'Baru', 'gerbang', 'none', 'cinzel', '{"bg": "#fbf3e3", "card": "#fefbf5", "primary": "#a8141c", "on-primary": "#ffffff", "gold": "#e2b22c", "gold-deep": "#7c6219", "ink": "#4c090d", "muted": "#8a5c59"}'::jsonb, FALSE, 401, 'alex-brush', '', '', '/img/tema/suku/omo-sebua-nias-hiasan.svg', 'kilau-emas', 'suku-omo-sebua-nias', 'satu', 'zoom', '/img/tema/suku/omo-sebua-nias-motif.svg', 'pola', 'zoom-masuk', 'zoom-masuk', TRUE, TRUE)
ON CONFLICT (slug) DO NOTHING;
-- Tanah Karo — Sumatera Utara: Siwaluh Jabu Karo
INSERT INTO themes (slug, name, category, nuansa, palette, region, description, tags, badge, layout, ornament, font, tokens, dark, sort_order, script_font, bg_image, frame_image, card_deco, float_deco, open_anim, page_mode, scroll_anim, image_url, image_mode, gerak_judul, gerak_foto, ken_burns, listed)
VALUES ('siwaluh-jabu-karo', 'Siwaluh Jabu Karo', 'Adat', 'Batak', 'blush', 'Tanah Karo — Sumatera Utara', 'Rumah siwaluh jabu beratap ijuk bertanduk, uis gara merah-magenta, dan tudung beka buluh perempuan Karo.', '["Uis Gara", "Karo", "Tudung", "Provinsi Tanah Karo — Sumatera Utara"]'::jsonb, 'Baru', 'editorial', 'none', 'dm-serif', '{"bg": "#fbf1f4", "card": "#fefafb", "primary": "#7a1f4b", "on-primary": "#ffffff", "gold": "#d9a441", "gold-deep": "#826227", "ink": "#370e22", "muted": "#7c5e6d"}'::jsonb, FALSE, 402, 'parisienne', '', '/img/tema/suku/siwaluh-jabu-karo-bingkai.svg', '/img/tema/suku/siwaluh-jabu-karo-hiasan.svg', 'kelopak', 'suku-siwaluh-jabu-karo', 'satu', 'lipat', '/img/tema/suku/siwaluh-jabu-karo-sudut.svg', 'sudut', 'zoom-masuk', 'zoom-masuk', TRUE, TRUE)
ON CONFLICT (slug) DO NOTHING;
-- Mandailing — Sumatera Utara: Gordang Sambilan Mandailing
INSERT INTO themes (slug, name, category, nuansa, palette, region, description, tags, badge, layout, ornament, font, tokens, dark, sort_order, script_font, bg_image, frame_image, card_deco, float_deco, open_anim, page_mode, scroll_anim, image_url, image_mode, gerak_judul, gerak_foto, ken_burns, listed)
VALUES ('gordang-mandailing', 'Gordang Sambilan Mandailing', 'Luxury', 'Batak', 'gold', 'Mandailing — Sumatera Utara', 'Sembilan gendang gordang sambilan bertalu di bagas godang, ulos tenun Mandailing hitam-merah-emas yang anggun.', '["Mode Gelap", "Gordang Sambilan", "Bagas Godang", "Provinsi Mandailing — Sumatera Utara"]'::jsonb, 'Baru', 'bingkai', 'none', 'cormorant', '{"bg": "#160d0b", "card": "#261e1c", "primary": "#d9aa4b", "on-primary": "#120a09", "gold": "#d9aa4b", "gold-deep": "#d9aa4b", "ink": "#f6ead2", "muted": "#9c9282"}'::jsonb, TRUE, 403, 'great-vibes', '/img/tema/suku/gordang-mandailing-latar.svg', '', '/img/tema/suku/gordang-mandailing-hiasan.svg', 'kunang', 'gorga-batak', 'satu', 'bayang', '/img/tema/suku/gordang-mandailing-motif.svg', 'pola', 'zoom-masuk', 'zoom-masuk', TRUE, TRUE)
ON CONFLICT (slug) DO NOTHING;
-- Siberut — Sumatera Barat: Titi Mentawai
INSERT INTO themes (slug, name, category, nuansa, palette, region, description, tags, badge, layout, ornament, font, tokens, dark, sort_order, script_font, bg_image, frame_image, card_deco, float_deco, open_anim, page_mode, scroll_anim, image_url, image_mode, gerak_judul, gerak_foto, ken_burns, listed)
VALUES ('titi-mentawai', 'Titi Mentawai', 'Adat', 'Mentawai', 'sage', 'Siberut — Sumatera Barat', 'Garis tato titi Mentawai, uma kayu di tengah hutan Siberut, dan bunga hutan — undangan bernuansa alam yang tenang.', '["Tato Titi", "Hutan Tropis", "Alam", "Provinsi Siberut — Sumatera Barat"]'::jsonb, 'Baru', 'editorial', 'none', 'lora', '{"bg": "#f4f1e6", "card": "#fbfaf6", "primary": "#3d5a2a", "on-primary": "#ffffff", "gold": "#c6a15a", "gold-deep": "#776136", "ink": "#1b2813", "muted": "#626958"}'::jsonb, FALSE, 404, 'allura', '', '/img/tema/suku/titi-mentawai-bingkai.svg', '/img/tema/suku/titi-mentawai-hiasan.svg', 'daun-gugur', 'taman-daun', 'satu', 'naik', '/img/tema/suku/titi-mentawai-motif.svg', 'pola', 'zoom-masuk', 'zoom-masuk', TRUE, TRUE)
ON CONFLICT (slug) DO NOTHING;
-- Medan — Melayu Deli: Istana Maimun Deli
INSERT INTO themes (slug, name, category, nuansa, palette, region, description, tags, badge, layout, ornament, font, tokens, dark, sort_order, script_font, bg_image, frame_image, card_deco, float_deco, open_anim, page_mode, scroll_anim, image_url, image_mode, gerak_judul, gerak_foto, ken_burns, listed)
VALUES ('istana-maimun-deli', 'Istana Maimun Deli', 'Adat', 'Melayu', 'gold', 'Medan — Melayu Deli', 'Istana Maimun berkubah kuning dan hijau, awan larat Melayu Deli, dan tepak sirih — kemegahan Kesultanan Deli.', '["Kuning Diraja", "Awan Larat", "Kesultanan", "Provinsi Medan — Melayu Deli"]'::jsonb, 'Baru', 'bingkai', 'none', 'marcellus', '{"bg": "#fffaea", "card": "#fffdf8", "primary": "#7d5600", "on-primary": "#ffffff", "gold": "#d4a017", "gold-deep": "#8a680f", "ink": "#382700", "muted": "#796c4c"}'::jsonb, FALSE, 405, 'great-vibes', '', '', '/img/tema/suku/istana-maimun-deli-hiasan.svg', 'daun-sirih', 'suku-istana-maimun-deli', 'satu', 'anggun', '/img/tema/suku/istana-maimun-deli-sudut.svg', 'sudut', 'zoom-masuk', 'zoom-masuk', TRUE, TRUE)
ON CONFLICT (slug) DO NOTHING;
-- Lampung Pesisir — Saibatin: Tapis Saibatin Pesisir
INSERT INTO themes (slug, name, category, nuansa, palette, region, description, tags, badge, layout, ornament, font, tokens, dark, sort_order, script_font, bg_image, frame_image, card_deco, float_deco, open_anim, page_mode, scroll_anim, image_url, image_mode, gerak_judul, gerak_foto, ken_burns, listed)
VALUES ('tapis-saibatin', 'Tapis Saibatin Pesisir', 'Adat', 'Lampung', 'navy', 'Lampung Pesisir — Saibatin', 'Kain tapis bermotif kapal dan sulam emas masyarakat adat Saibatin di pesisir Lampung — biru laut dan emas.', '["Tapis Kapal", "Pesisir", "Sulam Emas", "Provinsi Lampung Pesisir — Saibatin"]'::jsonb, 'Baru', 'gerbang', 'none', 'playfair', '{"bg": "#f5f4ef", "card": "#fcfbf9", "primary": "#1b3a6b", "on-primary": "#ffffff", "gold": "#d7a83c", "gold-deep": "#816424", "ink": "#0c1a30", "muted": "#5f6874"}'::jsonb, FALSE, 406, 'alex-brush', '/img/tema/suku/tapis-saibatin-latar.svg', '/img/tema/suku/tapis-saibatin-bingkai.svg', '/img/tema/suku/tapis-saibatin-hiasan.svg', 'bintang', 'suku-tapis-saibatin', 'satu', 'ombak', '/img/tema/suku/tapis-saibatin-motif.svg', 'pola', 'zoom-masuk', 'zoom-masuk', TRUE, TRUE)
ON CONFLICT (slug) DO NOTHING;
-- Banyuwangi — Osing: Gandrung Osing Banyuwangi
INSERT INTO themes (slug, name, category, nuansa, palette, region, description, tags, badge, layout, ornament, font, tokens, dark, sort_order, script_font, bg_image, frame_image, card_deco, float_deco, open_anim, page_mode, scroll_anim, image_url, image_mode, gerak_judul, gerak_foto, ken_burns, listed)
VALUES ('gandrung-osing', 'Gandrung Osing Banyuwangi', 'Adat', 'Jawa', 'terra', 'Banyuwangi — Osing', 'Penari gandrung bermahkota omprog, batik gajah oling merah-hitam, dan rumah tikel balung masyarakat Osing.', '["Gajah Oling", "Gandrung", "Merah Hitam", "Provinsi Banyuwangi — Osing"]'::jsonb, 'Baru', 'klasik', 'none', 'cinzel', '{"bg": "#fbf3ea", "card": "#fefbf8", "primary": "#a11a1a", "on-primary": "#ffffff", "gold": "#e0b03c", "gold-deep": "#7b6121", "ink": "#480c0c", "muted": "#875e5b"}'::jsonb, FALSE, 407, 'allura', '', '', '/img/tema/suku/gandrung-osing-hiasan.svg', 'kamboja-gugur', 'suku-gandrung-osing', 'satu', 'zoom', '/img/tema/suku/gandrung-osing-motif.svg', 'pola', 'zoom-masuk', 'zoom-masuk', TRUE, TRUE)
ON CONFLICT (slug) DO NOTHING;
-- Pulau Madura: Karapan Madura
INSERT INTO themes (slug, name, category, nuansa, palette, region, description, tags, badge, layout, ornament, font, tokens, dark, sort_order, script_font, bg_image, frame_image, card_deco, float_deco, open_anim, page_mode, scroll_anim, image_url, image_mode, gerak_judul, gerak_foto, ken_burns, listed)
VALUES ('karapan-madura', 'Karapan Madura', 'Adat', 'Madura', 'terra', 'Pulau Madura', 'Batik Madura bercorak berani merah-kuning-hijau, rumah tanean lanjang, dan kemeriahan karapan sapi.', '["Batik Madura", "Warna Berani", "Tanean Lanjang", "Provinsi Pulau Madura"]'::jsonb, 'Baru', 'gerbang', 'none', 'dm-serif', '{"bg": "#fff6e6", "card": "#fffcf6", "primary": "#b3261e", "on-primary": "#ffffff", "gold": "#f0b429", "gold-deep": "#846317", "ink": "#51110d", "muted": "#8f625a"}'::jsonb, FALSE, 408, 'great-vibes', '', '/img/tema/suku/karapan-madura-bingkai.svg', '/img/tema/suku/karapan-madura-hiasan.svg', 'kelopak', 'amplop', 'satu', 'lipat', '/img/tema/suku/karapan-madura-sudut.svg', 'sudut', 'zoom-masuk', 'zoom-masuk', TRUE, TRUE)
ON CONFLICT (slug) DO NOTHING;
-- Pekalongan — Batik Pesisir: Jlamprang Pekalongan
INSERT INTO themes (slug, name, category, nuansa, palette, region, description, tags, badge, layout, ornament, font, tokens, dark, sort_order, script_font, bg_image, frame_image, card_deco, float_deco, open_anim, page_mode, scroll_anim, image_url, image_mode, gerak_judul, gerak_foto, ken_burns, listed)
VALUES ('jlamprang-pekalongan', 'Jlamprang Pekalongan', 'Adat', 'Jawa', 'navy', 'Pekalongan — Batik Pesisir', 'Batik pesisir Pekalongan: jlamprang geometris dan buketan bunga berwarna toska-merah muda — ceria dan modern.', '["Batik Pesisir", "Buketan", "Toska", "Provinsi Pekalongan — Batik Pesisir"]'::jsonb, 'Baru', 'editorial', 'none', 'playfair', '{"bg": "#f2faf8", "card": "#fafdfd", "primary": "#0e6565", "on-primary": "#ffffff", "gold": "#d9a066", "gold-deep": "#82603d", "ink": "#062d2d", "muted": "#53706f"}'::jsonb, FALSE, 409, 'parisienne', '/img/tema/suku/jlamprang-pekalongan-latar.svg', '', '/img/tema/suku/jlamprang-pekalongan-hiasan.svg', 'kupu', 'tirai', 'satu', 'mekar', '/img/tema/suku/jlamprang-pekalongan-motif.svg', 'pola', 'zoom-masuk', 'zoom-masuk', TRUE, TRUE)
ON CONFLICT (slug) DO NOTHING;
-- Klaten — Jawa Tengah: Lurik Klaten
INSERT INTO themes (slug, name, category, nuansa, palette, region, description, tags, badge, layout, ornament, font, tokens, dark, sort_order, script_font, bg_image, frame_image, card_deco, float_deco, open_anim, page_mode, scroll_anim, image_url, image_mode, gerak_judul, gerak_foto, ken_burns, listed)
VALUES ('lurik-klaten', 'Lurik Klaten', 'Adat', 'Jawa', 'navy', 'Klaten — Jawa Tengah', 'Kain lurik bergaris tenunan tangan Klaten — sederhana, bersahaja, dan rapi dalam nila dan putih tulang.', '["Lurik", "Minimalis", "Tenun Tangan", "Provinsi Klaten — Jawa Tengah"]'::jsonb, 'Baru', 'editorial', 'none', 'lora', '{"bg": "#f6f4ef", "card": "#fcfbf9", "primary": "#2b3a67", "on-primary": "#ffffff", "gold": "#c9a96e", "gold-deep": "#796542", "ink": "#131a2e", "muted": "#636873"}'::jsonb, FALSE, 410, 'great-vibes', '', '/img/tema/suku/lurik-klaten-bingkai.svg', '/img/tema/suku/lurik-klaten-hiasan.svg', 'none', 'pudar', 'satu', 'naik', '/img/tema/suku/lurik-klaten-motif.svg', 'pola', 'zoom-masuk', 'zoom-masuk', TRUE, TRUE)
ON CONFLICT (slug) DO NOTHING;
-- Kanekes — Banten: Tenun Baduy
INSERT INTO themes (slug, name, category, nuansa, palette, region, description, tags, badge, layout, ornament, font, tokens, dark, sort_order, script_font, bg_image, frame_image, card_deco, float_deco, open_anim, page_mode, scroll_anim, image_url, image_mode, gerak_judul, gerak_foto, ken_burns, listed)
VALUES ('tenun-baduy', 'Tenun Baduy', 'Adat', 'Sunda', 'navy', 'Kanekes — Banten', 'Tenun Baduy hitam-biru nila, rumah panggung bambu tanpa paku, dan leuit lumbung padi — hidup selaras dengan alam.', '["Tenun Nila", "Bambu", "Kesederhanaan", "Provinsi Kanekes — Banten"]'::jsonb, 'Baru', 'klasik', 'none', 'cormorant', '{"bg": "#f3f1ec", "card": "#fbfaf8", "primary": "#1f2a44", "on-primary": "#ffffff", "gold": "#b8a27a", "gold-deep": "#6e6149", "ink": "#0e131f", "muted": "#66696e"}'::jsonb, FALSE, 411, 'parisienne', '', '', '/img/tema/suku/tenun-baduy-hiasan.svg', 'daun-gugur', 'mega-mendung', 'satu', 'pudar', '/img/tema/suku/tenun-baduy-sudut.svg', 'sudut', 'zoom-masuk', 'zoom-masuk', TRUE, TRUE)
ON CONFLICT (slug) DO NOTHING;
-- Tenganan — Bali Aga: Geringsing Tenganan
INSERT INTO themes (slug, name, category, nuansa, palette, region, description, tags, badge, layout, ornament, font, tokens, dark, sort_order, script_font, bg_image, frame_image, card_deco, float_deco, open_anim, page_mode, scroll_anim, image_url, image_mode, gerak_judul, gerak_foto, ken_burns, listed)
VALUES ('geringsing-tenganan', 'Geringsing Tenganan', 'Luxury', 'Bali', 'gold', 'Tenganan — Bali Aga', 'Kain geringsing tenun ikat ganda dari desa Bali Aga Tenganan — merah soga dan hitam, dipercaya menolak bala.', '["Mode Gelap", "Ikat Ganda", "Bali Aga", "Provinsi Tenganan — Bali Aga"]'::jsonb, 'Baru', 'bingkai', 'none', 'marcellus', '{"bg": "#1a0f0c", "card": "#2a201d", "primary": "#d9a65a", "on-primary": "#150c0a", "gold": "#d9a65a", "gold-deep": "#d9a65a", "ink": "#f6e9d6", "muted": "#9e9285"}'::jsonb, TRUE, 412, 'alex-brush', '/img/tema/suku/geringsing-tenganan-latar.svg', '', '/img/tema/suku/geringsing-tenganan-hiasan.svg', 'kunang', 'lawang-bali', 'satu', 'bayang', '/img/tema/suku/geringsing-tenganan-motif.svg', 'pola', 'zoom-masuk', 'zoom-masuk', TRUE, TRUE)
ON CONFLICT (slug) DO NOTHING;
-- Bima — Nusa Tenggara Barat: Tembe Nggoli Mbojo
INSERT INTO themes (slug, name, category, nuansa, palette, region, description, tags, badge, layout, ornament, font, tokens, dark, sort_order, script_font, bg_image, frame_image, card_deco, float_deco, open_anim, page_mode, scroll_anim, image_url, image_mode, gerak_judul, gerak_foto, ken_burns, listed)
VALUES ('tembe-mbojo', 'Tembe Nggoli Mbojo', 'Adat', 'Mbojo', 'sage', 'Bima — Nusa Tenggara Barat', 'Sarung tembe nggoli tenunan Bima, Istana Asi Mbojo, dan rimpu perempuan Mbojo — hijau zamrud dan emas.', '["Tembe Nggoli", "Rimpu", "Kesultanan Bima", "Provinsi Bima — Nusa Tenggara Barat"]'::jsonb, 'Baru', 'gerbang', 'none', 'cinzel', '{"bg": "#f5f8f3", "card": "#fcfdfb", "primary": "#155e4b", "on-primary": "#ffffff", "gold": "#d8ae4c", "gold-deep": "#81682d", "ink": "#092a22", "muted": "#566e67"}'::jsonb, FALSE, 413, 'parisienne', '', '', '/img/tema/suku/tembe-mbojo-hiasan.svg', 'daun-sirih', 'tenun-songket', 'satu', 'geser', '/img/tema/suku/tembe-mbojo-motif.svg', 'pola', 'zoom-masuk', 'zoom-masuk', TRUE, TRUE)
ON CONFLICT (slug) DO NOTHING;
-- Manggarai — Flores: Songke Manggarai
INSERT INTO themes (slug, name, category, nuansa, palette, region, description, tags, badge, layout, ornament, font, tokens, dark, sort_order, script_font, bg_image, frame_image, card_deco, float_deco, open_anim, page_mode, scroll_anim, image_url, image_mode, gerak_judul, gerak_foto, ken_burns, listed)
VALUES ('songke-manggarai', 'Songke Manggarai', 'Luxury', 'NTT', 'gold', 'Manggarai — Flores', 'Kain songke hitam bersulam warna-warni, rumah kerucut mbaru niang Wae Rebo, dan sawah lodok berbentuk jaring laba-laba.', '["Mode Gelap", "Songke", "Mbaru Niang", "Provinsi Manggarai — Flores"]'::jsonb, 'Baru', 'gerbang', 'none', 'dm-serif', '{"bg": "#121014", "card": "#232124", "primary": "#e7b847", "on-primary": "#0e0d10", "gold": "#e7b847", "gold-deep": "#e7b847", "ink": "#f9edd1", "muted": "#9d9585"}'::jsonb, TRUE, 414, 'allura', '', '/img/tema/suku/songke-manggarai-bingkai.svg', '/img/tema/suku/songke-manggarai-hiasan.svg', 'bintang', 'suku-songke-manggarai', 'satu', 'lipat', '/img/tema/suku/songke-manggarai-sudut.svg', 'sudut', 'zoom-masuk', 'zoom-masuk', TRUE, TRUE)
ON CONFLICT (slug) DO NOTHING;
-- Timor — Nusa Tenggara Timur: Ikat Timor
INSERT INTO themes (slug, name, category, nuansa, palette, region, description, tags, badge, layout, ornament, font, tokens, dark, sort_order, script_font, bg_image, frame_image, card_deco, float_deco, open_anim, page_mode, scroll_anim, image_url, image_mode, gerak_judul, gerak_foto, ken_burns, listed)
VALUES ('ikat-timor', 'Ikat Timor', 'Adat', 'NTT', 'terra', 'Timor — Nusa Tenggara Timur', 'Tenun ikat Timor merah-jingga bermotif kaif, rumah bulat ume kbubu, dan sasando — kehangatan Pulau Timor.', '["Tenun Ikat", "Ume Kbubu", "Jingga", "Provinsi Timor — Nusa Tenggara Timur"]'::jsonb, 'Baru', 'klasik', 'none', 'lora', '{"bg": "#fbf0e8", "card": "#fefaf7", "primary": "#a23518", "on-primary": "#ffffff", "gold": "#e2a93b", "gold-deep": "#7c5d20", "ink": "#49180b", "muted": "#835f54"}'::jsonb, FALSE, 415, 'alex-brush', '/img/tema/suku/ikat-timor-latar.svg', '', '/img/tema/suku/ikat-timor-hiasan.svg', 'kelopak', 'tenun-maluku', 'satu', 'anggun', '/img/tema/suku/ikat-timor-motif.svg', 'pola', 'zoom-masuk', 'zoom-masuk', TRUE, TRUE)
ON CONFLICT (slug) DO NOTHING;
-- Kapuas Hulu — Dayak Iban: Pua Kumbu Iban
INSERT INTO themes (slug, name, category, nuansa, palette, region, description, tags, badge, layout, ornament, font, tokens, dark, sort_order, script_font, bg_image, frame_image, card_deco, float_deco, open_anim, page_mode, scroll_anim, image_url, image_mode, gerak_judul, gerak_foto, ken_burns, listed)
VALUES ('pua-kumbu-iban', 'Pua Kumbu Iban', 'Adat', 'Dayak', 'terra', 'Kapuas Hulu — Dayak Iban', 'Kain pua kumbu Dayak Iban yang ditenun penuh doa, rumah panjai, dan burung kenyalang — cokelat tanah dan krem.', '["Pua Kumbu", "Rumah Panjai", "Kenyalang", "Provinsi Kapuas Hulu — Dayak Iban"]'::jsonb, 'Baru', 'bingkai', 'none', 'dm-serif', '{"bg": "#f7efe6", "card": "#fcf9f6", "primary": "#7a2414", "on-primary": "#ffffff", "gold": "#d4a35a", "gold-deep": "#7f6236", "ink": "#371009", "muted": "#7c5f58"}'::jsonb, FALSE, 416, 'great-vibes', '', '', '/img/tema/suku/pua-kumbu-iban-hiasan.svg', 'bulu-enggang', 'suku-pua-kumbu-iban', 'satu', 'lipat', '/img/tema/suku/pua-kumbu-iban-motif.svg', 'pola', 'zoom-masuk', 'zoom-masuk', TRUE, TRUE)
ON CONFLICT (slug) DO NOTHING;
-- Tenggarong — Kutai Kartanegara: Ulap Doyo Kutai
INSERT INTO themes (slug, name, category, nuansa, palette, region, description, tags, badge, layout, ornament, font, tokens, dark, sort_order, script_font, bg_image, frame_image, card_deco, float_deco, open_anim, page_mode, scroll_anim, image_url, image_mode, gerak_judul, gerak_foto, ken_burns, listed)
VALUES ('ulap-doyo-kutai', 'Ulap Doyo Kutai', 'Luxury', 'Melayu', 'gold', 'Tenggarong — Kutai Kartanegara', 'Kain ulap doyo dari serat daun doyo, Keraton Kutai Kartanegara, dan erau — marun gelap berbintik emas.', '["Mode Gelap", "Ulap Doyo", "Keraton Kutai", "Provinsi Tenggarong — Kutai Kartanegara"]'::jsonb, 'Baru', 'editorial', 'none', 'cormorant', '{"bg": "#1d0f14", "card": "#2d2024", "primary": "#e3b44f", "on-primary": "#170c10", "gold": "#e3b44f", "gold-deep": "#e3b44f", "ink": "#f8ecd3", "muted": "#a09487"}'::jsonb, TRUE, 417, 'allura', '', '', '/img/tema/suku/ulap-doyo-kutai-hiasan.svg', 'kilau-emas', 'galaksi', 'satu', 'lipat', '/img/tema/suku/ulap-doyo-kutai-sudut.svg', 'sudut', 'zoom-masuk', 'zoom-masuk', TRUE, TRUE)
ON CONFLICT (slug) DO NOTHING;
-- Gowa — Makassar: Baju Bodo Makassar
INSERT INTO themes (slug, name, category, nuansa, palette, region, description, tags, badge, layout, ornament, font, tokens, dark, sort_order, script_font, bg_image, frame_image, card_deco, float_deco, open_anim, page_mode, scroll_anim, image_url, image_mode, gerak_judul, gerak_foto, ken_burns, listed)
VALUES ('baju-bodo-makassar', 'Baju Bodo Makassar', 'Adat', 'Bugis-Makassar', 'blush', 'Gowa — Makassar', 'Baju bodo merah muda tembus pandang, Balla Lompoa Kerajaan Gowa, dan lipa sabbe sutra — ceria dan berwibawa.', '["Baju Bodo", "Balla Lompoa", "Sutra", "Provinsi Gowa — Makassar"]'::jsonb, 'Baru', 'klasik', 'none', 'playfair', '{"bg": "#fdf1f6", "card": "#fefafc", "primary": "#a3195b", "on-primary": "#ffffff", "gold": "#e6b450", "gold-deep": "#7f632c", "ink": "#490b29", "muted": "#895d72"}'::jsonb, FALSE, 418, 'great-vibes', '/img/tema/suku/baju-bodo-makassar-latar.svg', '/img/tema/suku/baju-bodo-makassar-bingkai.svg', '/img/tema/suku/baju-bodo-makassar-hiasan.svg', 'kelopak', 'suku-baju-bodo-makassar', 'satu', 'tenun', '/img/tema/suku/baju-bodo-makassar-motif.svg', 'pola', 'zoom-masuk', 'zoom-masuk', TRUE, TRUE)
ON CONFLICT (slug) DO NOTHING;
-- Watampone — Bugis Bone: Saoraja Bone
INSERT INTO themes (slug, name, category, nuansa, palette, region, description, tags, badge, layout, ornament, font, tokens, dark, sort_order, script_font, bg_image, frame_image, card_deco, float_deco, open_anim, page_mode, scroll_anim, image_url, image_mode, gerak_judul, gerak_foto, ken_burns, listed)
VALUES ('saoraja-bone', 'Saoraja Bone', 'Luxury', 'Bugis-Makassar', 'gold', 'Watampone — Bugis Bone', 'Istana Saoraja Kerajaan Bone, lontara Bugis, dan sarung sutra hijau tua berbenang emas.', '["Mode Gelap", "Lontara", "Sutra Bugis", "Provinsi Watampone — Bugis Bone"]'::jsonb, 'Baru', 'bingkai', 'none', 'cinzel', '{"bg": "#0f1a14", "card": "#202a24", "primary": "#dfb04a", "on-primary": "#0c1510", "gold": "#dfb04a", "gold-deep": "#dfb04a", "ink": "#f7ebd2", "muted": "#9a9786"}'::jsonb, TRUE, 419, 'parisienne', '', '', '/img/tema/suku/saoraja-bone-hiasan.svg', 'kilau-emas', 'gebyok-jawa', 'satu', 'kosmik', '/img/tema/suku/saoraja-bone-motif.svg', 'pola', 'zoom-masuk', 'zoom-masuk', TRUE, TRUE)
ON CONFLICT (slug) DO NOTHING;
-- Kepulauan Sangihe — Sulawesi Utara: Kofo Sangihe
INSERT INTO themes (slug, name, category, nuansa, palette, region, description, tags, badge, layout, ornament, font, tokens, dark, sort_order, script_font, bg_image, frame_image, card_deco, float_deco, open_anim, page_mode, scroll_anim, image_url, image_mode, gerak_judul, gerak_foto, ken_burns, listed)
VALUES ('kofo-sangihe', 'Kofo Sangihe', 'Adat', 'Sangihe', 'navy', 'Kepulauan Sangihe — Sulawesi Utara', 'Kain kofo dari serat pisang abaka, perahu pelang, dan gunung api Karangetang — ungu laut dan emas.', '["Kain Kofo", "Kepulauan", "Bahari", "Provinsi Kepulauan Sangihe — Sulawesi Utara"]'::jsonb, 'Baru', 'gerbang', 'none', 'lora', '{"bg": "#f3f3fb", "card": "#fbfbfe", "primary": "#3b3f8f", "on-primary": "#ffffff", "gold": "#d8b25a", "gold-deep": "#776232", "ink": "#1b1c40", "muted": "#686883"}'::jsonb, FALSE, 420, 'parisienne', '', '/img/tema/suku/kofo-sangihe-bingkai.svg', '/img/tema/suku/kofo-sangihe-hiasan.svg', 'kupu', 'layar-naik', 'satu', 'ombak', '/img/tema/suku/kofo-sangihe-sudut.svg', 'sudut', 'zoom-masuk', 'zoom-masuk', TRUE, TRUE)
ON CONFLICT (slug) DO NOTHING;
-- Kepulauan Kei — Maluku: Ain ni Ain Kei
INSERT INTO themes (slug, name, category, nuansa, palette, region, description, tags, badge, layout, ornament, font, tokens, dark, sort_order, script_font, bg_image, frame_image, card_deco, float_deco, open_anim, page_mode, scroll_anim, image_url, image_mode, gerak_judul, gerak_foto, ken_burns, listed)
VALUES ('ain-ni-ain-kei', 'Ain ni Ain Kei', 'Adat', 'Maluku', 'navy', 'Kepulauan Kei — Maluku', 'Pasir putih terhalus di Ngurbloat, laut toska, dan falsafah ain ni ain (kita semua bersaudara) masyarakat Kei.', '["Pantai", "Toska", "Persaudaraan", "Provinsi Kepulauan Kei — Maluku"]'::jsonb, 'Baru', 'klasik', 'none', 'marcellus', '{"bg": "#effafa", "card": "#f9fdfd", "primary": "#0a6573", "on-primary": "#ffffff", "gold": "#e2b65b", "gold-deep": "#7c6432", "ink": "#042d34", "muted": "#517074"}'::jsonb, FALSE, 421, 'allura', '/img/tema/suku/ain-ni-ain-kei-latar.svg', '', '/img/tema/suku/ain-ni-ain-kei-hiasan.svg', 'bintang', 'suku-ain-ni-ain-kei', 'satu', 'geser', '/img/tema/suku/ain-ni-ain-kei-motif.svg', 'pola', 'zoom-masuk', 'zoom-masuk', TRUE, TRUE)
ON CONFLICT (slug) DO NOTHING;
-- Kepulauan Tanimbar — Maluku: Tenun Tanimbar
INSERT INTO themes (slug, name, category, nuansa, palette, region, description, tags, badge, layout, ornament, font, tokens, dark, sort_order, script_font, bg_image, frame_image, card_deco, float_deco, open_anim, page_mode, scroll_anim, image_url, image_mode, gerak_judul, gerak_foto, ken_burns, listed)
VALUES ('tenun-tanimbar', 'Tenun Tanimbar', 'Adat', 'Maluku', 'terra', 'Kepulauan Tanimbar — Maluku', 'Tenun ikat Tanimbar bermotif ulerati, perahu batu, dan tifa — marun hangat dari ujung tenggara Maluku.', '["Tenun Ikat", "Tifa", "Marun", "Provinsi Kepulauan Tanimbar — Maluku"]'::jsonb, 'Baru', 'editorial', 'none', 'cinzel', '{"bg": "#fbf2ee", "card": "#fefaf9", "primary": "#6e1f2b", "on-primary": "#ffffff", "gold": "#d29d4a", "gold-deep": "#7d5e2c", "ink": "#320e13", "muted": "#795f61"}'::jsonb, FALSE, 422, 'great-vibes', '', '/img/tema/suku/tenun-tanimbar-bingkai.svg', '/img/tema/suku/tenun-tanimbar-hiasan.svg', 'cengkih-gugur', 'tenun-maluku', 'satu', 'zoom', '/img/tema/suku/tenun-tanimbar-motif.svg', 'pola', 'zoom-masuk', 'zoom-masuk', TRUE, TRUE)
ON CONFLICT (slug) DO NOTHING;
-- Biak — Papua: Wor Biak
INSERT INTO themes (slug, name, category, nuansa, palette, region, description, tags, badge, layout, ornament, font, tokens, dark, sort_order, script_font, bg_image, frame_image, card_deco, float_deco, open_anim, page_mode, scroll_anim, image_url, image_mode, gerak_judul, gerak_foto, ken_burns, listed)
VALUES ('wor-biak', 'Wor Biak', 'Adat', 'Papua', 'navy', 'Biak — Papua', 'Lagu dan tarian wor masyarakat Biak, perahu wairon bercadik, dan laut biru dalam Teluk Cenderawasih.', '["Bahari", "Tari Wor", "Biru Laut", "Provinsi Biak — Papua"]'::jsonb, 'Baru', 'gerbang', 'none', 'dm-serif', '{"bg": "#f2f6fb", "card": "#fafcfe", "primary": "#0d3b66", "on-primary": "#ffffff", "gold": "#f0b23c", "gold-deep": "#846221", "ink": "#061b2e", "muted": "#5a6977"}'::jsonb, FALSE, 423, 'parisienne', '', '', '/img/tema/suku/wor-biak-hiasan.svg', 'burung', 'suku-wor-biak', 'satu', 'anggun', '/img/tema/suku/wor-biak-sudut.svg', 'sudut', 'zoom-masuk', 'zoom-masuk', TRUE, TRUE)
ON CONFLICT (slug) DO NOTHING;
-- Danau Sentani — Papua: Kulit Kayu Sentani
INSERT INTO themes (slug, name, category, nuansa, palette, region, description, tags, badge, layout, ornament, font, tokens, dark, sort_order, script_font, bg_image, frame_image, card_deco, float_deco, open_anim, page_mode, scroll_anim, image_url, image_mode, gerak_judul, gerak_foto, ken_burns, listed)
VALUES ('kulit-kayu-sentani', 'Kulit Kayu Sentani', 'Adat', 'Papua', 'terra', 'Danau Sentani — Papua', 'Lukisan kulit kayu khombouw bermotif ikan dan fouw dari Danau Sentani — tanah liat, jingga, dan hitam.', '["Lukisan Kulit Kayu", "Danau Sentani", "Tanah Liat", "Provinsi Danau Sentani — Papua"]'::jsonb, 'Baru', 'bingkai', 'none', 'lora', '{"bg": "#f8efe5", "card": "#fdf9f6", "primary": "#8c3b1c", "on-primary": "#ffffff", "gold": "#d9a45a", "gold-deep": "#826236", "ink": "#3f1b0d", "muted": "#7c6054"}'::jsonb, FALSE, 424, 'alex-brush', '/img/tema/suku/kulit-kayu-sentani-latar.svg', '', '/img/tema/suku/kulit-kayu-sentani-hiasan.svg', 'daun-gugur', 'pudar', 'satu', 'mekar', '/img/tema/suku/kulit-kayu-sentani-motif.svg', 'pola', 'zoom-masuk', 'zoom-masuk', TRUE, TRUE)
ON CONFLICT (slug) DO NOTHING;

-- ── Ornamen khas daerah (hanya tema yang belum punya ornamen) ──
INSERT INTO theme_ornaments (theme, bagian, img, posisi, x, y, lebar, rotasi, cermin, masuk, jeda, durasi, gerak, kecepatan, depan, hp, opasitas, urutan, source)
SELECT a.theme, a.bagian, a.img, a.posisi, a.x, a.y, a.lebar, a.rotasi, a.cermin, a.masuk, a.jeda, a.durasi, a.gerak, a.kecepatan, a.depan, a.hp, a.opasitas, a.urutan, 'seed'
  FROM (VALUES
    ('kerawang-gayo', 'sampul', '/img/tema/suku/kerawang-gayo-orn-sudut.svg', 'kiri-atas', -36, -36, 30, 0, FALSE, 'ayun-kiri', 400, 1300, 'goyang', 8, FALSE, TRUE, 85, 10),
    ('kerawang-gayo', 'sampul', '/img/tema/suku/kerawang-gayo-orn-sudut.svg', 'kanan-atas', 36, -36, 30, 0, TRUE, 'ayun-kanan', 700, 1300, 'goyang', 9, FALSE, TRUE, 85, 20),
    ('kerawang-gayo', 'sampul', '/img/tema/suku/kerawang-gayo-orn-tokoh.svg', 'kiri-bawah', -50, 24, 24, 0, TRUE, 'naik', 1100, 1400, 'none', 6, FALSE, TRUE, 100, 30),
    ('kerawang-gayo', 'sampul', '/img/tema/suku/kerawang-gayo-orn-tokoh.svg', 'kanan-bawah', 50, 24, 24, 0, FALSE, 'naik', 1500, 1400, 'none', 7, FALSE, TRUE, 100, 40),
    ('kerawang-gayo', 'mempelai', '/img/tema/suku/kerawang-gayo-orn-lambang.svg', 'tengah-atas', 0, -46, 22, 0, FALSE, 'zoom', 300, 1200, 'putar', 36, FALSE, TRUE, 90, 50),
    ('kerawang-gayo', 'kisah', '/img/tema/suku/kerawang-gayo-orn-tokoh.svg', 'kanan-atas', 18, -10, 20, 0, FALSE, 'naik', 200, 1300, 'none', 7, FALSE, FALSE, 85, 60),
    ('kerawang-gayo', 'galeri', '/img/tema/suku/kerawang-gayo-orn-atas.svg', 'tengah-atas', 0, -78, 84, 0, FALSE, 'turun', 200, 1400, 'goyang', 6, FALSE, TRUE, 95, 70),
    ('kerawang-gayo', 'acara', '/img/tema/suku/kerawang-gayo-orn-ikon.svg', 'tengah-atas', 0, -6, 92, 0, FALSE, 'naik', 200, 1600, 'none', 9, FALSE, TRUE, 28, 80),
    ('kerawang-gayo', 'acara', '/img/tema/suku/kerawang-gayo-orn-sudut.svg', 'kanan-bawah', 16, 20, 28, 180, FALSE, 'ayun-kanan', 600, 1300, 'goyang', 8, FALSE, FALSE, 85, 90),
    ('kerawang-gayo', 'rsvp', '/img/tema/suku/kerawang-gayo-orn-ikon.svg', 'tengah-bawah', 0, 12, 80, 0, FALSE, 'naik', 300, 1600, 'none', 9, FALSE, TRUE, 22, 100),
    ('omo-sebua-nias', 'sampul', '/img/tema/suku/omo-sebua-nias-orn-sudut.svg', 'kiri-atas', -36, -36, 30, 0, FALSE, 'ayun-kiri', 400, 1300, 'goyang', 8, FALSE, TRUE, 85, 10),
    ('omo-sebua-nias', 'sampul', '/img/tema/suku/omo-sebua-nias-orn-sudut.svg', 'kanan-atas', 36, -36, 30, 0, TRUE, 'ayun-kanan', 700, 1300, 'goyang', 9, FALSE, TRUE, 85, 20),
    ('omo-sebua-nias', 'sampul', '/img/tema/suku/omo-sebua-nias-orn-tokoh.svg', 'kiri-bawah', -50, 24, 28, 0, TRUE, 'turun', 1100, 1400, 'goyang', 6, FALSE, TRUE, 100, 30),
    ('omo-sebua-nias', 'sampul', '/img/tema/suku/omo-sebua-nias-orn-tokoh.svg', 'kanan-bawah', 50, 24, 28, 0, FALSE, 'turun', 1500, 1400, 'goyang', 7, FALSE, TRUE, 100, 40),
    ('omo-sebua-nias', 'mempelai', '/img/tema/suku/omo-sebua-nias-orn-lambang.svg', 'tengah-atas', 0, -46, 22, 0, FALSE, 'zoom', 300, 1200, 'putar', 36, FALSE, TRUE, 90, 50),
    ('omo-sebua-nias', 'kisah', '/img/tema/suku/omo-sebua-nias-orn-tokoh.svg', 'kanan-atas', 18, -10, 20, 0, FALSE, 'turun', 200, 1300, 'goyang', 7, FALSE, FALSE, 85, 60),
    ('omo-sebua-nias', 'galeri', '/img/tema/suku/omo-sebua-nias-orn-atas.svg', 'tengah-atas', 0, -78, 84, 0, FALSE, 'turun', 200, 1400, 'goyang', 6, FALSE, TRUE, 95, 70),
    ('omo-sebua-nias', 'acara', '/img/tema/suku/omo-sebua-nias-orn-ikon.svg', 'tengah-atas', 0, -6, 92, 0, FALSE, 'naik', 200, 1600, 'none', 9, FALSE, TRUE, 28, 80),
    ('omo-sebua-nias', 'acara', '/img/tema/suku/omo-sebua-nias-orn-sudut.svg', 'kanan-bawah', 16, 20, 28, 180, FALSE, 'ayun-kanan', 600, 1300, 'goyang', 8, FALSE, FALSE, 85, 90),
    ('omo-sebua-nias', 'rsvp', '/img/tema/suku/omo-sebua-nias-orn-ikon.svg', 'tengah-bawah', 0, 12, 80, 0, FALSE, 'naik', 300, 1600, 'none', 9, FALSE, TRUE, 22, 100),
    ('siwaluh-jabu-karo', 'sampul', '/img/tema/suku/siwaluh-jabu-karo-orn-sudut.svg', 'kiri-atas', -36, -36, 30, 0, FALSE, 'ayun-kiri', 400, 1300, 'goyang', 8, FALSE, TRUE, 85, 10),
    ('siwaluh-jabu-karo', 'sampul', '/img/tema/suku/siwaluh-jabu-karo-orn-sudut.svg', 'kanan-atas', 36, -36, 30, 0, TRUE, 'ayun-kanan', 700, 1300, 'goyang', 9, FALSE, TRUE, 85, 20),
    ('siwaluh-jabu-karo', 'sampul', '/img/tema/suku/siwaluh-jabu-karo-orn-tokoh.svg', 'kiri-bawah', -50, 24, 28, 0, TRUE, 'turun', 1100, 1400, 'goyang', 6, FALSE, TRUE, 100, 30),
    ('siwaluh-jabu-karo', 'sampul', '/img/tema/suku/siwaluh-jabu-karo-orn-tokoh.svg', 'kanan-bawah', 50, 24, 28, 0, FALSE, 'turun', 1500, 1400, 'goyang', 7, FALSE, TRUE, 100, 40),
    ('siwaluh-jabu-karo', 'mempelai', '/img/tema/suku/siwaluh-jabu-karo-orn-lambang.svg', 'tengah-atas', 0, -46, 22, 0, FALSE, 'zoom', 300, 1200, 'putar', 36, FALSE, TRUE, 90, 50),
    ('siwaluh-jabu-karo', 'kisah', '/img/tema/suku/siwaluh-jabu-karo-orn-tokoh.svg', 'kanan-atas', 18, -10, 20, 0, FALSE, 'turun', 200, 1300, 'goyang', 7, FALSE, FALSE, 85, 60),
    ('siwaluh-jabu-karo', 'galeri', '/img/tema/suku/siwaluh-jabu-karo-orn-atas.svg', 'tengah-atas', 0, -78, 84, 0, FALSE, 'turun', 200, 1400, 'goyang', 6, FALSE, TRUE, 95, 70),
    ('siwaluh-jabu-karo', 'acara', '/img/tema/suku/siwaluh-jabu-karo-orn-ikon.svg', 'tengah-atas', 0, -6, 92, 0, FALSE, 'naik', 200, 1600, 'none', 9, FALSE, TRUE, 28, 80),
    ('siwaluh-jabu-karo', 'acara', '/img/tema/suku/siwaluh-jabu-karo-orn-sudut.svg', 'kanan-bawah', 16, 20, 28, 180, FALSE, 'ayun-kanan', 600, 1300, 'goyang', 8, FALSE, FALSE, 85, 90),
    ('siwaluh-jabu-karo', 'rsvp', '/img/tema/suku/siwaluh-jabu-karo-orn-ikon.svg', 'tengah-bawah', 0, 12, 80, 0, FALSE, 'naik', 300, 1600, 'none', 9, FALSE, TRUE, 22, 100),
    ('gordang-mandailing', 'sampul', '/img/tema/suku/gordang-mandailing-orn-sudut.svg', 'kiri-atas', -36, -36, 30, 0, FALSE, 'ayun-kiri', 400, 1300, 'goyang', 8, FALSE, TRUE, 85, 10),
    ('gordang-mandailing', 'sampul', '/img/tema/suku/gordang-mandailing-orn-sudut.svg', 'kanan-atas', 36, -36, 30, 0, TRUE, 'ayun-kanan', 700, 1300, 'goyang', 9, FALSE, TRUE, 85, 20),
    ('gordang-mandailing', 'sampul', '/img/tema/suku/gordang-mandailing-orn-tokoh.svg', 'kiri-bawah', -50, 24, 28, 0, TRUE, 'turun', 1100, 1400, 'goyang', 6, FALSE, TRUE, 100, 30),
    ('gordang-mandailing', 'sampul', '/img/tema/suku/gordang-mandailing-orn-tokoh.svg', 'kanan-bawah', 50, 24, 28, 0, FALSE, 'turun', 1500, 1400, 'goyang', 7, FALSE, TRUE, 100, 40),
    ('gordang-mandailing', 'mempelai', '/img/tema/suku/gordang-mandailing-orn-lambang.svg', 'tengah-atas', 0, -46, 22, 0, FALSE, 'zoom', 300, 1200, 'putar', 36, FALSE, TRUE, 90, 50),
    ('gordang-mandailing', 'kisah', '/img/tema/suku/gordang-mandailing-orn-tokoh.svg', 'kanan-atas', 18, -10, 20, 0, FALSE, 'turun', 200, 1300, 'goyang', 7, FALSE, FALSE, 85, 60),
    ('gordang-mandailing', 'galeri', '/img/tema/suku/gordang-mandailing-orn-atas.svg', 'tengah-atas', 0, -78, 84, 0, FALSE, 'turun', 200, 1400, 'goyang', 6, FALSE, TRUE, 95, 70),
    ('gordang-mandailing', 'acara', '/img/tema/suku/gordang-mandailing-orn-ikon.svg', 'tengah-atas', 0, -6, 92, 0, FALSE, 'naik', 200, 1600, 'none', 9, FALSE, TRUE, 28, 80),
    ('gordang-mandailing', 'acara', '/img/tema/suku/gordang-mandailing-orn-sudut.svg', 'kanan-bawah', 16, 20, 28, 180, FALSE, 'ayun-kanan', 600, 1300, 'goyang', 8, FALSE, FALSE, 85, 90),
    ('gordang-mandailing', 'rsvp', '/img/tema/suku/gordang-mandailing-orn-ikon.svg', 'tengah-bawah', 0, 12, 80, 0, FALSE, 'naik', 300, 1600, 'none', 9, FALSE, TRUE, 22, 100),
    ('titi-mentawai', 'sampul', '/img/tema/suku/titi-mentawai-orn-sudut.svg', 'kiri-atas', -36, -36, 30, 0, FALSE, 'ayun-kiri', 400, 1300, 'goyang', 8, FALSE, TRUE, 85, 10),
    ('titi-mentawai', 'sampul', '/img/tema/suku/titi-mentawai-orn-sudut.svg', 'kanan-atas', 36, -36, 30, 0, TRUE, 'ayun-kanan', 700, 1300, 'goyang', 9, FALSE, TRUE, 85, 20),
    ('titi-mentawai', 'sampul', '/img/tema/suku/titi-mentawai-orn-tokoh.svg', 'kiri-bawah', -50, 24, 44, 0, TRUE, 'tumbuh', 1100, 1400, 'goyang', 6, FALSE, TRUE, 100, 30),
    ('titi-mentawai', 'sampul', '/img/tema/suku/titi-mentawai-orn-tokoh.svg', 'kanan-bawah', 50, 24, 44, 0, FALSE, 'tumbuh', 1500, 1400, 'goyang', 7, FALSE, TRUE, 100, 40),
    ('titi-mentawai', 'mempelai', '/img/tema/suku/titi-mentawai-orn-sudut.svg', 'tengah-atas', 0, -46, 26, 0, FALSE, 'zoom', 300, 1200, 'goyang', 36, FALSE, TRUE, 90, 50),
    ('titi-mentawai', 'kisah', '/img/tema/suku/titi-mentawai-orn-tokoh.svg', 'kanan-atas', 18, -10, 34, 0, FALSE, 'tumbuh', 200, 1300, 'goyang', 7, FALSE, FALSE, 85, 60),
    ('titi-mentawai', 'galeri', '/img/tema/suku/titi-mentawai-orn-atas.svg', 'tengah-atas', 0, -78, 84, 0, FALSE, 'turun', 200, 1400, 'goyang', 6, FALSE, TRUE, 95, 70),
    ('titi-mentawai', 'acara', '/img/tema/suku/titi-mentawai-orn-ikon.svg', 'tengah-atas', 0, -6, 92, 0, FALSE, 'naik', 200, 1600, 'none', 9, FALSE, TRUE, 28, 80),
    ('titi-mentawai', 'acara', '/img/tema/suku/titi-mentawai-orn-sudut.svg', 'kanan-bawah', 16, 20, 28, 180, FALSE, 'ayun-kanan', 600, 1300, 'goyang', 8, FALSE, FALSE, 85, 90),
    ('titi-mentawai', 'rsvp', '/img/tema/suku/titi-mentawai-orn-ikon.svg', 'tengah-bawah', 0, 12, 80, 0, FALSE, 'naik', 300, 1600, 'none', 9, FALSE, TRUE, 22, 100),
    ('istana-maimun-deli', 'sampul', '/img/tema/suku/istana-maimun-deli-orn-sudut.svg', 'kiri-atas', -36, -36, 30, 0, FALSE, 'ayun-kiri', 400, 1300, 'goyang', 8, FALSE, TRUE, 85, 10),
    ('istana-maimun-deli', 'sampul', '/img/tema/suku/istana-maimun-deli-orn-sudut.svg', 'kanan-atas', 36, -36, 30, 0, TRUE, 'ayun-kanan', 700, 1300, 'goyang', 9, FALSE, TRUE, 85, 20),
    ('istana-maimun-deli', 'sampul', '/img/tema/suku/istana-maimun-deli-orn-tokoh.svg', 'kiri-bawah', -50, 24, 30, 0, TRUE, 'turun', 1100, 1400, 'goyang', 6, FALSE, TRUE, 100, 30),
    ('istana-maimun-deli', 'sampul', '/img/tema/suku/istana-maimun-deli-orn-tokoh.svg', 'kanan-bawah', 50, 24, 30, 0, FALSE, 'turun', 1500, 1400, 'goyang', 7, FALSE, TRUE, 100, 40),
    ('istana-maimun-deli', 'mempelai', '/img/tema/suku/istana-maimun-deli-orn-lambang.svg', 'tengah-atas', 0, -46, 22, 0, FALSE, 'zoom', 300, 1200, 'putar', 36, FALSE, TRUE, 90, 50),
    ('istana-maimun-deli', 'kisah', '/img/tema/suku/istana-maimun-deli-orn-tokoh.svg', 'kanan-atas', 18, -10, 20, 0, FALSE, 'turun', 200, 1300, 'goyang', 7, FALSE, FALSE, 85, 60),
    ('istana-maimun-deli', 'galeri', '/img/tema/suku/istana-maimun-deli-orn-atas.svg', 'tengah-atas', 0, -78, 84, 0, FALSE, 'turun', 200, 1400, 'goyang', 6, FALSE, TRUE, 95, 70),
    ('istana-maimun-deli', 'acara', '/img/tema/suku/istana-maimun-deli-orn-ikon.svg', 'tengah-atas', 0, -6, 92, 0, FALSE, 'naik', 200, 1600, 'none', 9, FALSE, TRUE, 28, 80),
    ('istana-maimun-deli', 'acara', '/img/tema/suku/istana-maimun-deli-orn-sudut.svg', 'kanan-bawah', 16, 20, 28, 180, FALSE, 'ayun-kanan', 600, 1300, 'goyang', 8, FALSE, FALSE, 85, 90),
    ('istana-maimun-deli', 'rsvp', '/img/tema/suku/istana-maimun-deli-orn-ikon.svg', 'tengah-bawah', 0, 12, 80, 0, FALSE, 'naik', 300, 1600, 'none', 9, FALSE, TRUE, 22, 100),
    ('tapis-saibatin', 'sampul', '/img/tema/suku/tapis-saibatin-orn-sudut.svg', 'kiri-atas', -36, -36, 30, 0, FALSE, 'ayun-kiri', 400, 1300, 'goyang', 8, FALSE, TRUE, 85, 10),
    ('tapis-saibatin', 'sampul', '/img/tema/suku/tapis-saibatin-orn-sudut.svg', 'kanan-atas', 36, -36, 30, 0, TRUE, 'ayun-kanan', 700, 1300, 'goyang', 9, FALSE, TRUE, 85, 20),
    ('tapis-saibatin', 'sampul', '/img/tema/suku/tapis-saibatin-orn-tokoh.svg', 'kiri-bawah', -50, 24, 28, 0, TRUE, 'turun', 1100, 1400, 'goyang', 6, FALSE, TRUE, 100, 30),
    ('tapis-saibatin', 'sampul', '/img/tema/suku/tapis-saibatin-orn-tokoh.svg', 'kanan-bawah', 50, 24, 28, 0, FALSE, 'turun', 1500, 1400, 'goyang', 7, FALSE, TRUE, 100, 40),
    ('tapis-saibatin', 'mempelai', '/img/tema/suku/tapis-saibatin-orn-lambang.svg', 'tengah-atas', 0, -46, 22, 0, FALSE, 'zoom', 300, 1200, 'putar', 36, FALSE, TRUE, 90, 50),
    ('tapis-saibatin', 'kisah', '/img/tema/suku/tapis-saibatin-orn-tokoh.svg', 'kanan-atas', 18, -10, 20, 0, FALSE, 'turun', 200, 1300, 'goyang', 7, FALSE, FALSE, 85, 60),
    ('tapis-saibatin', 'galeri', '/img/tema/suku/tapis-saibatin-orn-atas.svg', 'tengah-atas', 0, -78, 84, 0, FALSE, 'turun', 200, 1400, 'goyang', 6, FALSE, TRUE, 95, 70),
    ('tapis-saibatin', 'acara', '/img/tema/suku/tapis-saibatin-orn-ikon.svg', 'tengah-atas', 0, -6, 92, 0, FALSE, 'zoom', 200, 1600, 'kilau', 9, FALSE, TRUE, 28, 80),
    ('tapis-saibatin', 'acara', '/img/tema/suku/tapis-saibatin-orn-sudut.svg', 'kanan-bawah', 16, 20, 28, 180, FALSE, 'ayun-kanan', 600, 1300, 'goyang', 8, FALSE, FALSE, 85, 90),
    ('tapis-saibatin', 'rsvp', '/img/tema/suku/tapis-saibatin-orn-ikon.svg', 'tengah-bawah', 0, 12, 80, 0, FALSE, 'zoom', 300, 1600, 'kilau', 9, FALSE, TRUE, 22, 100),
    ('gandrung-osing', 'sampul', '/img/tema/suku/gandrung-osing-orn-sudut.svg', 'kiri-atas', -36, -36, 30, 0, FALSE, 'ayun-kiri', 400, 1300, 'goyang', 8, FALSE, TRUE, 85, 10),
    ('gandrung-osing', 'sampul', '/img/tema/suku/gandrung-osing-orn-sudut.svg', 'kanan-atas', 36, -36, 30, 0, TRUE, 'ayun-kanan', 700, 1300, 'goyang', 9, FALSE, TRUE, 85, 20),
    ('gandrung-osing', 'sampul', '/img/tema/suku/gandrung-osing-orn-tokoh.svg', 'kiri-bawah', -50, 24, 30, 0, TRUE, 'geser-kiri', 1100, 1400, 'goyang', 6, FALSE, TRUE, 100, 30),
    ('gandrung-osing', 'sampul', '/img/tema/suku/gandrung-osing-orn-tokoh.svg', 'kanan-bawah', 50, 24, 30, 0, FALSE, 'geser-kanan', 1500, 1400, 'goyang', 7, FALSE, TRUE, 100, 40),
    ('gandrung-osing', 'mempelai', '/img/tema/suku/gandrung-osing-orn-lambang.svg', 'tengah-atas', 0, -46, 22, 0, FALSE, 'zoom', 300, 1200, 'putar', 36, FALSE, TRUE, 90, 50),
    ('gandrung-osing', 'kisah', '/img/tema/suku/gandrung-osing-orn-tokoh.svg', 'kanan-atas', 18, -10, 20, 0, FALSE, 'geser-kanan', 200, 1300, 'goyang', 7, FALSE, FALSE, 85, 60),
    ('gandrung-osing', 'galeri', '/img/tema/suku/gandrung-osing-orn-atas.svg', 'tengah-atas', 0, -78, 84, 0, FALSE, 'turun', 200, 1400, 'goyang', 6, FALSE, TRUE, 95, 70),
    ('gandrung-osing', 'acara', '/img/tema/suku/gandrung-osing-orn-ikon.svg', 'tengah-atas', 0, -6, 92, 0, FALSE, 'tumbuh', 200, 1600, 'goyang', 9, FALSE, TRUE, 28, 80),
    ('gandrung-osing', 'acara', '/img/tema/suku/gandrung-osing-orn-sudut.svg', 'kanan-bawah', 16, 20, 28, 180, FALSE, 'ayun-kanan', 600, 1300, 'goyang', 8, FALSE, FALSE, 85, 90),
    ('gandrung-osing', 'rsvp', '/img/tema/suku/gandrung-osing-orn-ikon.svg', 'tengah-bawah', 0, 12, 80, 0, FALSE, 'tumbuh', 300, 1600, 'goyang', 9, FALSE, TRUE, 22, 100),
    ('karapan-madura', 'sampul', '/img/tema/suku/karapan-madura-orn-sudut.svg', 'kiri-atas', -36, -36, 30, 0, FALSE, 'ayun-kiri', 400, 1300, 'goyang', 8, FALSE, TRUE, 85, 10),
    ('karapan-madura', 'sampul', '/img/tema/suku/karapan-madura-orn-sudut.svg', 'kanan-atas', 36, -36, 30, 0, TRUE, 'ayun-kanan', 700, 1300, 'goyang', 9, FALSE, TRUE, 85, 20),
    ('karapan-madura', 'sampul', '/img/tema/suku/karapan-madura-orn-tokoh.svg', 'kiri-bawah', -50, 24, 36, 0, TRUE, 'naik', 1100, 1400, 'goyang', 6, FALSE, TRUE, 100, 30),
    ('karapan-madura', 'sampul', '/img/tema/suku/karapan-madura-orn-tokoh.svg', 'kanan-bawah', 50, 24, 36, 0, FALSE, 'naik', 1500, 1400, 'goyang', 7, FALSE, TRUE, 100, 40),
    ('karapan-madura', 'mempelai', '/img/tema/suku/karapan-madura-orn-sudut.svg', 'tengah-atas', 0, -46, 26, 0, FALSE, 'zoom', 300, 1200, 'goyang', 36, FALSE, TRUE, 90, 50),
    ('karapan-madura', 'kisah', '/img/tema/suku/karapan-madura-orn-tokoh.svg', 'kanan-atas', 18, -10, 26, 0, FALSE, 'naik', 200, 1300, 'goyang', 7, FALSE, FALSE, 85, 60),
    ('karapan-madura', 'galeri', '/img/tema/suku/karapan-madura-orn-atas.svg', 'tengah-atas', 0, -78, 84, 0, FALSE, 'geser-kiri', 200, 1400, 'melayang', 6, FALSE, TRUE, 95, 70),
    ('karapan-madura', 'acara', '/img/tema/suku/karapan-madura-orn-ikon.svg', 'tengah-atas', 0, -6, 92, 0, FALSE, 'naik', 200, 1600, 'melayang', 9, FALSE, TRUE, 28, 80),
    ('karapan-madura', 'acara', '/img/tema/suku/karapan-madura-orn-sudut.svg', 'kanan-bawah', 16, 20, 28, 180, FALSE, 'ayun-kanan', 600, 1300, 'goyang', 8, FALSE, FALSE, 85, 90),
    ('karapan-madura', 'rsvp', '/img/tema/suku/karapan-madura-orn-ikon.svg', 'tengah-bawah', 0, 12, 80, 0, FALSE, 'naik', 300, 1600, 'melayang', 9, FALSE, TRUE, 22, 100),
    ('jlamprang-pekalongan', 'sampul', '/img/tema/suku/jlamprang-pekalongan-orn-sudut.svg', 'kiri-atas', -36, -36, 30, 0, FALSE, 'ayun-kiri', 400, 1300, 'goyang', 8, FALSE, TRUE, 85, 10),
    ('jlamprang-pekalongan', 'sampul', '/img/tema/suku/jlamprang-pekalongan-orn-sudut.svg', 'kanan-atas', 36, -36, 30, 0, TRUE, 'ayun-kanan', 700, 1300, 'goyang', 9, FALSE, TRUE, 85, 20),
    ('jlamprang-pekalongan', 'sampul', '/img/tema/suku/jlamprang-pekalongan-orn-tokoh.svg', 'kiri-bawah', -50, 24, 34, 0, TRUE, 'tumbuh', 1100, 1400, 'goyang', 6, FALSE, TRUE, 100, 30),
    ('jlamprang-pekalongan', 'sampul', '/img/tema/suku/jlamprang-pekalongan-orn-tokoh.svg', 'kanan-bawah', 50, 24, 34, 0, FALSE, 'tumbuh', 1500, 1400, 'goyang', 7, FALSE, TRUE, 100, 40),
    ('jlamprang-pekalongan', 'mempelai', '/img/tema/suku/jlamprang-pekalongan-orn-sudut.svg', 'tengah-atas', 0, -46, 26, 0, FALSE, 'zoom', 300, 1200, 'goyang', 36, FALSE, TRUE, 90, 50),
    ('jlamprang-pekalongan', 'kisah', '/img/tema/suku/jlamprang-pekalongan-orn-tokoh.svg', 'kanan-atas', 18, -10, 24, 0, FALSE, 'tumbuh', 200, 1300, 'goyang', 7, FALSE, FALSE, 85, 60),
    ('jlamprang-pekalongan', 'galeri', '/img/tema/suku/jlamprang-pekalongan-orn-atas.svg', 'tengah-atas', 0, -78, 84, 0, FALSE, 'pudar', 200, 1400, 'melayang', 6, FALSE, TRUE, 95, 70),
    ('jlamprang-pekalongan', 'acara', '/img/tema/suku/jlamprang-pekalongan-orn-ikon.svg', 'tengah-atas', 0, -6, 92, 0, FALSE, 'pudar', 200, 1600, 'none', 9, FALSE, TRUE, 28, 80),
    ('jlamprang-pekalongan', 'acara', '/img/tema/suku/jlamprang-pekalongan-orn-sudut.svg', 'kanan-bawah', 16, 20, 28, 180, FALSE, 'ayun-kanan', 600, 1300, 'goyang', 8, FALSE, FALSE, 85, 90),
    ('jlamprang-pekalongan', 'rsvp', '/img/tema/suku/jlamprang-pekalongan-orn-ikon.svg', 'tengah-bawah', 0, 12, 80, 0, FALSE, 'pudar', 300, 1600, 'none', 9, FALSE, TRUE, 22, 100),
    ('lurik-klaten', 'sampul', '/img/tema/suku/lurik-klaten-orn-sudut.svg', 'kiri-atas', -36, -36, 30, 0, FALSE, 'ayun-kiri', 400, 1300, 'goyang', 8, FALSE, TRUE, 85, 10),
    ('lurik-klaten', 'sampul', '/img/tema/suku/lurik-klaten-orn-sudut.svg', 'kanan-atas', 36, -36, 30, 0, TRUE, 'ayun-kanan', 700, 1300, 'goyang', 9, FALSE, TRUE, 85, 20),
    ('lurik-klaten', 'sampul', '/img/tema/suku/lurik-klaten-orn-tokoh.svg', 'kiri-bawah', -50, 24, 34, 0, TRUE, 'tumbuh', 1100, 1400, 'goyang', 6, FALSE, TRUE, 100, 30),
    ('lurik-klaten', 'sampul', '/img/tema/suku/lurik-klaten-orn-tokoh.svg', 'kanan-bawah', 50, 24, 34, 0, FALSE, 'tumbuh', 1500, 1400, 'goyang', 7, FALSE, TRUE, 100, 40),
    ('lurik-klaten', 'mempelai', '/img/tema/suku/lurik-klaten-orn-sudut.svg', 'tengah-atas', 0, -46, 26, 0, FALSE, 'zoom', 300, 1200, 'goyang', 36, FALSE, TRUE, 90, 50),
    ('lurik-klaten', 'kisah', '/img/tema/suku/lurik-klaten-orn-tokoh.svg', 'kanan-atas', 18, -10, 24, 0, FALSE, 'tumbuh', 200, 1300, 'goyang', 7, FALSE, FALSE, 85, 60),
    ('lurik-klaten', 'galeri', '/img/tema/suku/lurik-klaten-orn-atas.svg', 'tengah-atas', 0, -78, 84, 0, FALSE, 'pudar', 200, 1400, 'melayang', 6, FALSE, TRUE, 95, 70),
    ('lurik-klaten', 'acara', '/img/tema/suku/lurik-klaten-orn-ikon.svg', 'tengah-atas', 0, -6, 92, 0, FALSE, 'pudar', 200, 1600, 'none', 9, FALSE, TRUE, 28, 80),
    ('lurik-klaten', 'acara', '/img/tema/suku/lurik-klaten-orn-sudut.svg', 'kanan-bawah', 16, 20, 28, 180, FALSE, 'ayun-kanan', 600, 1300, 'goyang', 8, FALSE, FALSE, 85, 90),
    ('lurik-klaten', 'rsvp', '/img/tema/suku/lurik-klaten-orn-ikon.svg', 'tengah-bawah', 0, 12, 80, 0, FALSE, 'pudar', 300, 1600, 'none', 9, FALSE, TRUE, 22, 100),
    ('tenun-baduy', 'sampul', '/img/tema/suku/tenun-baduy-orn-sudut.svg', 'kiri-atas', -36, -36, 30, 0, FALSE, 'ayun-kiri', 400, 1300, 'goyang', 8, FALSE, TRUE, 85, 10),
    ('tenun-baduy', 'sampul', '/img/tema/suku/tenun-baduy-orn-sudut.svg', 'kanan-atas', 36, -36, 30, 0, TRUE, 'ayun-kanan', 700, 1300, 'goyang', 9, FALSE, TRUE, 85, 20),
    ('tenun-baduy', 'sampul', '/img/tema/suku/tenun-baduy-orn-tokoh.svg', 'kiri-bawah', -50, 24, 30, 0, TRUE, 'naik', 1100, 1400, 'goyang', 6, FALSE, TRUE, 100, 30),
    ('tenun-baduy', 'sampul', '/img/tema/suku/tenun-baduy-orn-tokoh.svg', 'kanan-bawah', 50, 24, 30, 0, FALSE, 'naik', 1500, 1400, 'goyang', 7, FALSE, TRUE, 100, 40),
    ('tenun-baduy', 'mempelai', '/img/tema/suku/tenun-baduy-orn-lambang.svg', 'tengah-atas', 0, -46, 22, 0, FALSE, 'zoom', 300, 1200, 'putar', 36, FALSE, TRUE, 90, 50),
    ('tenun-baduy', 'kisah', '/img/tema/suku/tenun-baduy-orn-tokoh.svg', 'kanan-atas', 18, -10, 20, 0, FALSE, 'naik', 200, 1300, 'goyang', 7, FALSE, FALSE, 85, 60),
    ('tenun-baduy', 'galeri', '/img/tema/suku/tenun-baduy-orn-atas.svg', 'tengah-atas', 0, -78, 84, 0, FALSE, 'geser-kiri', 200, 1400, 'melayang', 6, FALSE, TRUE, 95, 70),
    ('tenun-baduy', 'acara', '/img/tema/suku/tenun-baduy-orn-ikon.svg', 'tengah-atas', 0, -6, 92, 0, FALSE, 'naik', 200, 1600, 'none', 9, FALSE, TRUE, 28, 80),
    ('tenun-baduy', 'acara', '/img/tema/suku/tenun-baduy-orn-sudut.svg', 'kanan-bawah', 16, 20, 28, 180, FALSE, 'ayun-kanan', 600, 1300, 'goyang', 8, FALSE, FALSE, 85, 90),
    ('tenun-baduy', 'rsvp', '/img/tema/suku/tenun-baduy-orn-ikon.svg', 'tengah-bawah', 0, 12, 80, 0, FALSE, 'naik', 300, 1600, 'none', 9, FALSE, TRUE, 22, 100),
    ('geringsing-tenganan', 'sampul', '/img/tema/suku/geringsing-tenganan-orn-sudut.svg', 'kiri-atas', -36, -36, 30, 0, FALSE, 'ayun-kiri', 400, 1300, 'goyang', 8, FALSE, TRUE, 85, 10),
    ('geringsing-tenganan', 'sampul', '/img/tema/suku/geringsing-tenganan-orn-sudut.svg', 'kanan-atas', 36, -36, 30, 0, TRUE, 'ayun-kanan', 700, 1300, 'goyang', 9, FALSE, TRUE, 85, 20),
    ('geringsing-tenganan', 'sampul', '/img/tema/suku/geringsing-tenganan-orn-tokoh.svg', 'kiri-bawah', -50, 24, 34, 0, TRUE, 'tumbuh', 1100, 1400, 'goyang', 6, FALSE, TRUE, 100, 30),
    ('geringsing-tenganan', 'sampul', '/img/tema/suku/geringsing-tenganan-orn-tokoh.svg', 'kanan-bawah', 50, 24, 34, 0, FALSE, 'tumbuh', 1500, 1400, 'goyang', 7, FALSE, TRUE, 100, 40),
    ('geringsing-tenganan', 'mempelai', '/img/tema/suku/geringsing-tenganan-orn-lambang.svg', 'tengah-atas', 0, -46, 22, 0, FALSE, 'zoom', 300, 1200, 'putar', 36, FALSE, TRUE, 90, 50),
    ('geringsing-tenganan', 'kisah', '/img/tema/suku/geringsing-tenganan-orn-tokoh.svg', 'kanan-atas', 18, -10, 24, 0, FALSE, 'tumbuh', 200, 1300, 'goyang', 7, FALSE, FALSE, 85, 60),
    ('geringsing-tenganan', 'galeri', '/img/tema/suku/geringsing-tenganan-orn-atas.svg', 'tengah-atas', 0, -78, 84, 0, FALSE, 'turun', 200, 1400, 'goyang', 6, FALSE, TRUE, 95, 70),
    ('geringsing-tenganan', 'acara', '/img/tema/suku/geringsing-tenganan-orn-ikon.svg', 'tengah-atas', 0, -6, 92, 0, FALSE, 'naik', 200, 1600, 'none', 9, FALSE, TRUE, 28, 80),
    ('geringsing-tenganan', 'acara', '/img/tema/suku/geringsing-tenganan-orn-sudut.svg', 'kanan-bawah', 16, 20, 28, 180, FALSE, 'ayun-kanan', 600, 1300, 'goyang', 8, FALSE, FALSE, 85, 90),
    ('geringsing-tenganan', 'rsvp', '/img/tema/suku/geringsing-tenganan-orn-ikon.svg', 'tengah-bawah', 0, 12, 80, 0, FALSE, 'naik', 300, 1600, 'none', 9, FALSE, TRUE, 22, 100),
    ('tembe-mbojo', 'sampul', '/img/tema/suku/tembe-mbojo-orn-sudut.svg', 'kiri-atas', -36, -36, 30, 0, FALSE, 'ayun-kiri', 400, 1300, 'goyang', 8, FALSE, TRUE, 85, 10),
    ('tembe-mbojo', 'sampul', '/img/tema/suku/tembe-mbojo-orn-sudut.svg', 'kanan-atas', 36, -36, 30, 0, TRUE, 'ayun-kanan', 700, 1300, 'goyang', 9, FALSE, TRUE, 85, 20),
    ('tembe-mbojo', 'sampul', '/img/tema/suku/tembe-mbojo-orn-tokoh.svg', 'kiri-bawah', -50, 24, 30, 0, TRUE, 'turun', 1100, 1400, 'goyang', 6, FALSE, TRUE, 100, 30),
    ('tembe-mbojo', 'sampul', '/img/tema/suku/tembe-mbojo-orn-tokoh.svg', 'kanan-bawah', 50, 24, 30, 0, FALSE, 'turun', 1500, 1400, 'goyang', 7, FALSE, TRUE, 100, 40),
    ('tembe-mbojo', 'mempelai', '/img/tema/suku/tembe-mbojo-orn-lambang.svg', 'tengah-atas', 0, -46, 22, 0, FALSE, 'zoom', 300, 1200, 'putar', 36, FALSE, TRUE, 90, 50),
    ('tembe-mbojo', 'kisah', '/img/tema/suku/tembe-mbojo-orn-tokoh.svg', 'kanan-atas', 18, -10, 20, 0, FALSE, 'turun', 200, 1300, 'goyang', 7, FALSE, FALSE, 85, 60),
    ('tembe-mbojo', 'galeri', '/img/tema/suku/tembe-mbojo-orn-atas.svg', 'tengah-atas', 0, -78, 84, 0, FALSE, 'turun', 200, 1400, 'goyang', 6, FALSE, TRUE, 95, 70),
    ('tembe-mbojo', 'acara', '/img/tema/suku/tembe-mbojo-orn-ikon.svg', 'tengah-atas', 0, -6, 92, 0, FALSE, 'naik', 200, 1600, 'none', 9, FALSE, TRUE, 28, 80),
    ('tembe-mbojo', 'acara', '/img/tema/suku/tembe-mbojo-orn-sudut.svg', 'kanan-bawah', 16, 20, 28, 180, FALSE, 'ayun-kanan', 600, 1300, 'goyang', 8, FALSE, FALSE, 85, 90),
    ('tembe-mbojo', 'rsvp', '/img/tema/suku/tembe-mbojo-orn-ikon.svg', 'tengah-bawah', 0, 12, 80, 0, FALSE, 'naik', 300, 1600, 'none', 9, FALSE, TRUE, 22, 100),
    ('songke-manggarai', 'sampul', '/img/tema/suku/songke-manggarai-orn-sudut.svg', 'kiri-atas', -36, -36, 30, 0, FALSE, 'ayun-kiri', 400, 1300, 'goyang', 8, FALSE, TRUE, 85, 10),
    ('songke-manggarai', 'sampul', '/img/tema/suku/songke-manggarai-orn-sudut.svg', 'kanan-atas', 36, -36, 30, 0, TRUE, 'ayun-kanan', 700, 1300, 'goyang', 9, FALSE, TRUE, 85, 20),
    ('songke-manggarai', 'sampul', '/img/tema/suku/songke-manggarai-orn-tokoh.svg', 'kiri-bawah', -50, 24, 34, 0, TRUE, 'tumbuh', 1100, 1400, 'goyang', 6, FALSE, TRUE, 100, 30),
    ('songke-manggarai', 'sampul', '/img/tema/suku/songke-manggarai-orn-tokoh.svg', 'kanan-bawah', 50, 24, 34, 0, FALSE, 'tumbuh', 1500, 1400, 'goyang', 7, FALSE, TRUE, 100, 40),
    ('songke-manggarai', 'mempelai', '/img/tema/suku/songke-manggarai-orn-lambang.svg', 'tengah-atas', 0, -46, 22, 0, FALSE, 'zoom', 300, 1200, 'putar', 36, FALSE, TRUE, 90, 50),
    ('songke-manggarai', 'kisah', '/img/tema/suku/songke-manggarai-orn-tokoh.svg', 'kanan-atas', 18, -10, 24, 0, FALSE, 'tumbuh', 200, 1300, 'goyang', 7, FALSE, FALSE, 85, 60),
    ('songke-manggarai', 'galeri', '/img/tema/suku/songke-manggarai-orn-atas.svg', 'tengah-atas', 0, -78, 84, 0, FALSE, 'turun', 200, 1400, 'goyang', 6, FALSE, TRUE, 95, 70),
    ('songke-manggarai', 'acara', '/img/tema/suku/songke-manggarai-orn-ikon.svg', 'tengah-atas', 0, -6, 92, 0, FALSE, 'zoom', 200, 1600, 'denyut', 9, FALSE, TRUE, 28, 80),
    ('songke-manggarai', 'acara', '/img/tema/suku/songke-manggarai-orn-sudut.svg', 'kanan-bawah', 16, 20, 28, 180, FALSE, 'ayun-kanan', 600, 1300, 'goyang', 8, FALSE, FALSE, 85, 90),
    ('songke-manggarai', 'rsvp', '/img/tema/suku/songke-manggarai-orn-ikon.svg', 'tengah-bawah', 0, 12, 80, 0, FALSE, 'zoom', 300, 1600, 'denyut', 9, FALSE, TRUE, 22, 100),
    ('ikat-timor', 'sampul', '/img/tema/suku/ikat-timor-orn-sudut.svg', 'kiri-atas', -36, -36, 30, 0, FALSE, 'ayun-kiri', 400, 1300, 'goyang', 8, FALSE, TRUE, 85, 10),
    ('ikat-timor', 'sampul', '/img/tema/suku/ikat-timor-orn-sudut.svg', 'kanan-atas', 36, -36, 30, 0, TRUE, 'ayun-kanan', 700, 1300, 'goyang', 9, FALSE, TRUE, 85, 20),
    ('ikat-timor', 'sampul', '/img/tema/suku/ikat-timor-orn-tokoh.svg', 'kiri-bawah', -50, 24, 34, 0, TRUE, 'tumbuh', 1100, 1400, 'goyang', 6, FALSE, TRUE, 100, 30),
    ('ikat-timor', 'sampul', '/img/tema/suku/ikat-timor-orn-tokoh.svg', 'kanan-bawah', 50, 24, 34, 0, FALSE, 'tumbuh', 1500, 1400, 'goyang', 7, FALSE, TRUE, 100, 40),
    ('ikat-timor', 'mempelai', '/img/tema/suku/ikat-timor-orn-lambang.svg', 'tengah-atas', 0, -46, 22, 0, FALSE, 'zoom', 300, 1200, 'putar', 36, FALSE, TRUE, 90, 50),
    ('ikat-timor', 'kisah', '/img/tema/suku/ikat-timor-orn-tokoh.svg', 'kanan-atas', 18, -10, 24, 0, FALSE, 'tumbuh', 200, 1300, 'goyang', 7, FALSE, FALSE, 85, 60),
    ('ikat-timor', 'galeri', '/img/tema/suku/ikat-timor-orn-atas.svg', 'tengah-atas', 0, -78, 84, 0, FALSE, 'turun', 200, 1400, 'goyang', 6, FALSE, TRUE, 95, 70),
    ('ikat-timor', 'acara', '/img/tema/suku/ikat-timor-orn-ikon.svg', 'tengah-atas', 0, -6, 92, 0, FALSE, 'zoom', 200, 1600, 'denyut', 9, FALSE, TRUE, 28, 80),
    ('ikat-timor', 'acara', '/img/tema/suku/ikat-timor-orn-sudut.svg', 'kanan-bawah', 16, 20, 28, 180, FALSE, 'ayun-kanan', 600, 1300, 'goyang', 8, FALSE, FALSE, 85, 90),
    ('ikat-timor', 'rsvp', '/img/tema/suku/ikat-timor-orn-ikon.svg', 'tengah-bawah', 0, 12, 80, 0, FALSE, 'zoom', 300, 1600, 'denyut', 9, FALSE, TRUE, 22, 100),
    ('pua-kumbu-iban', 'sampul', '/img/tema/suku/pua-kumbu-iban-orn-tokoh.svg', 'kiri-atas', -30, -18, 40, 0, TRUE, 'geser-kiri', 900, 1600, 'melayang', 5, FALSE, TRUE, 100, 10),
    ('pua-kumbu-iban', 'sampul', '/img/tema/suku/pua-kumbu-iban-orn-tokoh.svg', 'kanan-atas', 30, -10, 32, 0, FALSE, 'geser-kanan', 1500, 1600, 'melayang', 6, FALSE, TRUE, 100, 20),
    ('pua-kumbu-iban', 'sampul', '/img/tema/suku/pua-kumbu-iban-orn-sudut.svg', 'kiri-bawah', -36, 36, 30, 180, TRUE, 'ayun-kiri', 400, 1300, 'goyang', 8, FALSE, TRUE, 85, 30),
    ('pua-kumbu-iban', 'sampul', '/img/tema/suku/pua-kumbu-iban-orn-sudut.svg', 'kanan-bawah', 36, 36, 30, 180, FALSE, 'ayun-kanan', 700, 1300, 'goyang', 9, FALSE, TRUE, 85, 40),
    ('pua-kumbu-iban', 'mempelai', '/img/tema/suku/pua-kumbu-iban-orn-lambang.svg', 'tengah-atas', 0, -46, 22, 0, FALSE, 'zoom', 300, 1200, 'putar', 36, FALSE, TRUE, 90, 50),
    ('pua-kumbu-iban', 'kisah', '/img/tema/suku/pua-kumbu-iban-orn-tokoh.svg', 'kiri-atas', -18, -10, 30, 0, TRUE, 'geser-kiri', 200, 1300, 'melayang', 7, FALSE, FALSE, 85, 60),
    ('pua-kumbu-iban', 'galeri', '/img/tema/suku/pua-kumbu-iban-orn-atas.svg', 'tengah-atas', 0, -78, 84, 0, FALSE, 'turun', 200, 1400, 'goyang', 6, FALSE, TRUE, 95, 70),
    ('pua-kumbu-iban', 'acara', '/img/tema/suku/pua-kumbu-iban-orn-ikon.svg', 'tengah-atas', 0, -6, 92, 0, FALSE, 'naik', 200, 1600, 'none', 9, FALSE, TRUE, 28, 80),
    ('pua-kumbu-iban', 'acara', '/img/tema/suku/pua-kumbu-iban-orn-sudut.svg', 'kanan-bawah', 16, 20, 28, 180, FALSE, 'ayun-kanan', 600, 1300, 'goyang', 8, FALSE, FALSE, 85, 90),
    ('pua-kumbu-iban', 'rsvp', '/img/tema/suku/pua-kumbu-iban-orn-ikon.svg', 'tengah-bawah', 0, 12, 80, 0, FALSE, 'naik', 300, 1600, 'none', 9, FALSE, TRUE, 22, 100),
    ('ulap-doyo-kutai', 'sampul', '/img/tema/suku/ulap-doyo-kutai-orn-sudut.svg', 'kiri-atas', -36, -36, 30, 0, FALSE, 'ayun-kiri', 400, 1300, 'goyang', 8, FALSE, TRUE, 85, 10),
    ('ulap-doyo-kutai', 'sampul', '/img/tema/suku/ulap-doyo-kutai-orn-sudut.svg', 'kanan-atas', 36, -36, 30, 0, TRUE, 'ayun-kanan', 700, 1300, 'goyang', 9, FALSE, TRUE, 85, 20),
    ('ulap-doyo-kutai', 'sampul', '/img/tema/suku/ulap-doyo-kutai-orn-tokoh.svg', 'kiri-bawah', -50, 24, 30, 0, TRUE, 'turun', 1100, 1400, 'goyang', 6, FALSE, TRUE, 100, 30),
    ('ulap-doyo-kutai', 'sampul', '/img/tema/suku/ulap-doyo-kutai-orn-tokoh.svg', 'kanan-bawah', 50, 24, 30, 0, FALSE, 'turun', 1500, 1400, 'goyang', 7, FALSE, TRUE, 100, 40),
    ('ulap-doyo-kutai', 'mempelai', '/img/tema/suku/ulap-doyo-kutai-orn-lambang.svg', 'tengah-atas', 0, -46, 22, 0, FALSE, 'zoom', 300, 1200, 'putar', 36, FALSE, TRUE, 90, 50),
    ('ulap-doyo-kutai', 'kisah', '/img/tema/suku/ulap-doyo-kutai-orn-tokoh.svg', 'kanan-atas', 18, -10, 20, 0, FALSE, 'turun', 200, 1300, 'goyang', 7, FALSE, FALSE, 85, 60),
    ('ulap-doyo-kutai', 'galeri', '/img/tema/suku/ulap-doyo-kutai-orn-atas.svg', 'tengah-atas', 0, -78, 84, 0, FALSE, 'turun', 200, 1400, 'goyang', 6, FALSE, TRUE, 95, 70),
    ('ulap-doyo-kutai', 'acara', '/img/tema/suku/ulap-doyo-kutai-orn-ikon.svg', 'tengah-atas', 0, -6, 92, 0, FALSE, 'naik', 200, 1600, 'none', 9, FALSE, TRUE, 28, 80),
    ('ulap-doyo-kutai', 'acara', '/img/tema/suku/ulap-doyo-kutai-orn-sudut.svg', 'kanan-bawah', 16, 20, 28, 180, FALSE, 'ayun-kanan', 600, 1300, 'goyang', 8, FALSE, FALSE, 85, 90),
    ('ulap-doyo-kutai', 'rsvp', '/img/tema/suku/ulap-doyo-kutai-orn-ikon.svg', 'tengah-bawah', 0, 12, 80, 0, FALSE, 'naik', 300, 1600, 'none', 9, FALSE, TRUE, 22, 100),
    ('baju-bodo-makassar', 'sampul', '/img/tema/suku/baju-bodo-makassar-orn-sudut.svg', 'kiri-atas', -36, -36, 30, 0, FALSE, 'ayun-kiri', 400, 1300, 'goyang', 8, FALSE, TRUE, 85, 10),
    ('baju-bodo-makassar', 'sampul', '/img/tema/suku/baju-bodo-makassar-orn-sudut.svg', 'kanan-atas', 36, -36, 30, 0, TRUE, 'ayun-kanan', 700, 1300, 'goyang', 9, FALSE, TRUE, 85, 20),
    ('baju-bodo-makassar', 'sampul', '/img/tema/suku/baju-bodo-makassar-orn-tokoh.svg', 'kiri-bawah', -50, 24, 30, 0, TRUE, 'naik', 1100, 1400, 'melayang', 6, FALSE, TRUE, 100, 30),
    ('baju-bodo-makassar', 'sampul', '/img/tema/suku/baju-bodo-makassar-orn-tokoh.svg', 'kanan-bawah', 50, 24, 30, 0, FALSE, 'naik', 1500, 1400, 'melayang', 7, FALSE, TRUE, 100, 40),
    ('baju-bodo-makassar', 'mempelai', '/img/tema/suku/baju-bodo-makassar-orn-lambang.svg', 'tengah-atas', 0, -46, 22, 0, FALSE, 'zoom', 300, 1200, 'putar', 36, FALSE, TRUE, 90, 50),
    ('baju-bodo-makassar', 'kisah', '/img/tema/suku/baju-bodo-makassar-orn-tokoh.svg', 'kanan-atas', 18, -10, 20, 0, FALSE, 'naik', 200, 1300, 'melayang', 7, FALSE, FALSE, 85, 60),
    ('baju-bodo-makassar', 'galeri', '/img/tema/suku/baju-bodo-makassar-orn-atas.svg', 'tengah-atas', 0, -78, 84, 0, FALSE, 'turun', 200, 1400, 'goyang', 6, FALSE, TRUE, 95, 70),
    ('baju-bodo-makassar', 'acara', '/img/tema/suku/baju-bodo-makassar-orn-ikon.svg', 'tengah-atas', 0, -6, 92, 0, FALSE, 'geser-kiri', 200, 1600, 'melayang', 9, FALSE, TRUE, 28, 80),
    ('baju-bodo-makassar', 'acara', '/img/tema/suku/baju-bodo-makassar-orn-sudut.svg', 'kanan-bawah', 16, 20, 28, 180, FALSE, 'ayun-kanan', 600, 1300, 'goyang', 8, FALSE, FALSE, 85, 90),
    ('baju-bodo-makassar', 'rsvp', '/img/tema/suku/baju-bodo-makassar-orn-ikon.svg', 'tengah-bawah', 0, 12, 80, 0, FALSE, 'geser-kanan', 300, 1600, 'melayang', 9, FALSE, TRUE, 22, 100),
    ('saoraja-bone', 'sampul', '/img/tema/suku/saoraja-bone-orn-sudut.svg', 'kiri-atas', -36, -36, 30, 0, FALSE, 'ayun-kiri', 400, 1300, 'goyang', 8, FALSE, TRUE, 85, 10),
    ('saoraja-bone', 'sampul', '/img/tema/suku/saoraja-bone-orn-sudut.svg', 'kanan-atas', 36, -36, 30, 0, TRUE, 'ayun-kanan', 700, 1300, 'goyang', 9, FALSE, TRUE, 85, 20),
    ('saoraja-bone', 'sampul', '/img/tema/suku/saoraja-bone-orn-tokoh.svg', 'kiri-bawah', -50, 24, 30, 0, TRUE, 'naik', 1100, 1400, 'melayang', 6, FALSE, TRUE, 100, 30),
    ('saoraja-bone', 'sampul', '/img/tema/suku/saoraja-bone-orn-tokoh.svg', 'kanan-bawah', 50, 24, 30, 0, FALSE, 'naik', 1500, 1400, 'melayang', 7, FALSE, TRUE, 100, 40),
    ('saoraja-bone', 'mempelai', '/img/tema/suku/saoraja-bone-orn-lambang.svg', 'tengah-atas', 0, -46, 22, 0, FALSE, 'zoom', 300, 1200, 'putar', 36, FALSE, TRUE, 90, 50),
    ('saoraja-bone', 'kisah', '/img/tema/suku/saoraja-bone-orn-tokoh.svg', 'kanan-atas', 18, -10, 20, 0, FALSE, 'naik', 200, 1300, 'melayang', 7, FALSE, FALSE, 85, 60),
    ('saoraja-bone', 'galeri', '/img/tema/suku/saoraja-bone-orn-atas.svg', 'tengah-atas', 0, -78, 84, 0, FALSE, 'turun', 200, 1400, 'goyang', 6, FALSE, TRUE, 95, 70),
    ('saoraja-bone', 'acara', '/img/tema/suku/saoraja-bone-orn-ikon.svg', 'tengah-atas', 0, -6, 92, 0, FALSE, 'geser-kiri', 200, 1600, 'melayang', 9, FALSE, TRUE, 28, 80),
    ('saoraja-bone', 'acara', '/img/tema/suku/saoraja-bone-orn-sudut.svg', 'kanan-bawah', 16, 20, 28, 180, FALSE, 'ayun-kanan', 600, 1300, 'goyang', 8, FALSE, FALSE, 85, 90),
    ('saoraja-bone', 'rsvp', '/img/tema/suku/saoraja-bone-orn-ikon.svg', 'tengah-bawah', 0, 12, 80, 0, FALSE, 'geser-kanan', 300, 1600, 'melayang', 9, FALSE, TRUE, 22, 100),
    ('kofo-sangihe', 'sampul', '/img/tema/suku/kofo-sangihe-orn-sudut.svg', 'kiri-atas', -36, -36, 30, 0, FALSE, 'ayun-kiri', 400, 1300, 'goyang', 8, FALSE, TRUE, 85, 10),
    ('kofo-sangihe', 'sampul', '/img/tema/suku/kofo-sangihe-orn-sudut.svg', 'kanan-atas', 36, -36, 30, 0, TRUE, 'ayun-kanan', 700, 1300, 'goyang', 9, FALSE, TRUE, 85, 20),
    ('kofo-sangihe', 'sampul', '/img/tema/suku/kofo-sangihe-orn-tokoh.svg', 'kiri-bawah', -50, 24, 36, 0, TRUE, 'naik', 1100, 1400, 'goyang', 6, FALSE, TRUE, 100, 30),
    ('kofo-sangihe', 'sampul', '/img/tema/suku/kofo-sangihe-orn-tokoh.svg', 'kanan-bawah', 50, 24, 36, 0, FALSE, 'naik', 1500, 1400, 'goyang', 7, FALSE, TRUE, 100, 40),
    ('kofo-sangihe', 'mempelai', '/img/tema/suku/kofo-sangihe-orn-sudut.svg', 'tengah-atas', 0, -46, 26, 0, FALSE, 'zoom', 300, 1200, 'goyang', 36, FALSE, TRUE, 90, 50),
    ('kofo-sangihe', 'kisah', '/img/tema/suku/kofo-sangihe-orn-tokoh.svg', 'kanan-atas', 18, -10, 26, 0, FALSE, 'naik', 200, 1300, 'goyang', 7, FALSE, FALSE, 85, 60),
    ('kofo-sangihe', 'galeri', '/img/tema/suku/kofo-sangihe-orn-atas.svg', 'tengah-atas', 0, -78, 84, 0, FALSE, 'geser-kiri', 200, 1400, 'melayang', 6, FALSE, TRUE, 95, 70),
    ('kofo-sangihe', 'acara', '/img/tema/suku/kofo-sangihe-orn-ikon.svg', 'tengah-atas', 0, -6, 92, 0, FALSE, 'naik', 200, 1600, 'melayang', 9, FALSE, TRUE, 28, 80),
    ('kofo-sangihe', 'acara', '/img/tema/suku/kofo-sangihe-orn-sudut.svg', 'kanan-bawah', 16, 20, 28, 180, FALSE, 'ayun-kanan', 600, 1300, 'goyang', 8, FALSE, FALSE, 85, 90),
    ('kofo-sangihe', 'rsvp', '/img/tema/suku/kofo-sangihe-orn-ikon.svg', 'tengah-bawah', 0, 12, 80, 0, FALSE, 'naik', 300, 1600, 'melayang', 9, FALSE, TRUE, 22, 100),
    ('ain-ni-ain-kei', 'sampul', '/img/tema/suku/ain-ni-ain-kei-orn-sudut.svg', 'kiri-atas', -36, -36, 30, 0, FALSE, 'ayun-kiri', 400, 1300, 'goyang', 8, FALSE, TRUE, 85, 10),
    ('ain-ni-ain-kei', 'sampul', '/img/tema/suku/ain-ni-ain-kei-orn-sudut.svg', 'kanan-atas', 36, -36, 30, 0, TRUE, 'ayun-kanan', 700, 1300, 'goyang', 9, FALSE, TRUE, 85, 20),
    ('ain-ni-ain-kei', 'sampul', '/img/tema/suku/ain-ni-ain-kei-orn-tokoh.svg', 'kiri-bawah', -50, 24, 32, 0, TRUE, 'tumbuh', 1100, 1400, 'goyang', 6, FALSE, TRUE, 100, 30),
    ('ain-ni-ain-kei', 'sampul', '/img/tema/suku/ain-ni-ain-kei-orn-tokoh.svg', 'kanan-bawah', 50, 24, 32, 0, FALSE, 'tumbuh', 1500, 1400, 'goyang', 7, FALSE, TRUE, 100, 40),
    ('ain-ni-ain-kei', 'mempelai', '/img/tema/suku/ain-ni-ain-kei-orn-lambang.svg', 'tengah-atas', 0, -46, 22, 0, FALSE, 'zoom', 300, 1200, 'putar', 36, FALSE, TRUE, 90, 50),
    ('ain-ni-ain-kei', 'kisah', '/img/tema/suku/ain-ni-ain-kei-orn-tokoh.svg', 'kanan-atas', 18, -10, 22, 0, FALSE, 'tumbuh', 200, 1300, 'goyang', 7, FALSE, FALSE, 85, 60),
    ('ain-ni-ain-kei', 'galeri', '/img/tema/suku/ain-ni-ain-kei-orn-atas.svg', 'tengah-atas', 0, -78, 84, 0, FALSE, 'geser-kiri', 200, 1400, 'melayang', 6, FALSE, TRUE, 95, 70),
    ('ain-ni-ain-kei', 'acara', '/img/tema/suku/ain-ni-ain-kei-orn-ikon.svg', 'tengah-atas', 0, -6, 92, 0, FALSE, 'geser-kiri', 200, 1600, 'melayang', 9, FALSE, TRUE, 28, 80),
    ('ain-ni-ain-kei', 'acara', '/img/tema/suku/ain-ni-ain-kei-orn-sudut.svg', 'kanan-bawah', 16, 20, 28, 180, FALSE, 'ayun-kanan', 600, 1300, 'goyang', 8, FALSE, FALSE, 85, 90),
    ('ain-ni-ain-kei', 'rsvp', '/img/tema/suku/ain-ni-ain-kei-orn-ikon.svg', 'tengah-bawah', 0, 12, 80, 0, FALSE, 'geser-kanan', 300, 1600, 'melayang', 9, FALSE, TRUE, 22, 100),
    ('tenun-tanimbar', 'sampul', '/img/tema/suku/tenun-tanimbar-orn-sudut.svg', 'kiri-atas', -36, -36, 30, 0, FALSE, 'ayun-kiri', 400, 1300, 'goyang', 8, FALSE, TRUE, 85, 10),
    ('tenun-tanimbar', 'sampul', '/img/tema/suku/tenun-tanimbar-orn-sudut.svg', 'kanan-atas', 36, -36, 30, 0, TRUE, 'ayun-kanan', 700, 1300, 'goyang', 9, FALSE, TRUE, 85, 20),
    ('tenun-tanimbar', 'sampul', '/img/tema/suku/tenun-tanimbar-orn-tokoh.svg', 'kiri-bawah', -50, 24, 32, 0, TRUE, 'tumbuh', 1100, 1400, 'goyang', 6, FALSE, TRUE, 100, 30),
    ('tenun-tanimbar', 'sampul', '/img/tema/suku/tenun-tanimbar-orn-tokoh.svg', 'kanan-bawah', 50, 24, 32, 0, FALSE, 'tumbuh', 1500, 1400, 'goyang', 7, FALSE, TRUE, 100, 40),
    ('tenun-tanimbar', 'mempelai', '/img/tema/suku/tenun-tanimbar-orn-lambang.svg', 'tengah-atas', 0, -46, 22, 0, FALSE, 'zoom', 300, 1200, 'putar', 36, FALSE, TRUE, 90, 50),
    ('tenun-tanimbar', 'kisah', '/img/tema/suku/tenun-tanimbar-orn-tokoh.svg', 'kanan-atas', 18, -10, 22, 0, FALSE, 'tumbuh', 200, 1300, 'goyang', 7, FALSE, FALSE, 85, 60),
    ('tenun-tanimbar', 'galeri', '/img/tema/suku/tenun-tanimbar-orn-atas.svg', 'tengah-atas', 0, -78, 84, 0, FALSE, 'geser-kiri', 200, 1400, 'melayang', 6, FALSE, TRUE, 95, 70),
    ('tenun-tanimbar', 'acara', '/img/tema/suku/tenun-tanimbar-orn-ikon.svg', 'tengah-atas', 0, -6, 92, 0, FALSE, 'geser-kiri', 200, 1600, 'melayang', 9, FALSE, TRUE, 28, 80),
    ('tenun-tanimbar', 'acara', '/img/tema/suku/tenun-tanimbar-orn-sudut.svg', 'kanan-bawah', 16, 20, 28, 180, FALSE, 'ayun-kanan', 600, 1300, 'goyang', 8, FALSE, FALSE, 85, 90),
    ('tenun-tanimbar', 'rsvp', '/img/tema/suku/tenun-tanimbar-orn-ikon.svg', 'tengah-bawah', 0, 12, 80, 0, FALSE, 'geser-kanan', 300, 1600, 'melayang', 9, FALSE, TRUE, 22, 100),
    ('wor-biak', 'sampul', '/img/tema/suku/wor-biak-orn-tokoh.svg', 'kiri-atas', -30, -18, 40, 0, TRUE, 'geser-kiri', 900, 1600, 'melayang', 5, FALSE, TRUE, 100, 10),
    ('wor-biak', 'sampul', '/img/tema/suku/wor-biak-orn-tokoh.svg', 'kanan-atas', 30, -10, 32, 0, FALSE, 'geser-kanan', 1500, 1600, 'melayang', 6, FALSE, TRUE, 100, 20),
    ('wor-biak', 'sampul', '/img/tema/suku/wor-biak-orn-sudut.svg', 'kiri-bawah', -36, 36, 30, 180, TRUE, 'ayun-kiri', 400, 1300, 'goyang', 8, FALSE, TRUE, 85, 30),
    ('wor-biak', 'sampul', '/img/tema/suku/wor-biak-orn-sudut.svg', 'kanan-bawah', 36, 36, 30, 180, FALSE, 'ayun-kanan', 700, 1300, 'goyang', 9, FALSE, TRUE, 85, 40),
    ('wor-biak', 'mempelai', '/img/tema/suku/wor-biak-orn-lambang.svg', 'tengah-atas', 0, -46, 22, 0, FALSE, 'zoom', 300, 1200, 'putar', 36, FALSE, TRUE, 90, 50),
    ('wor-biak', 'kisah', '/img/tema/suku/wor-biak-orn-tokoh.svg', 'kiri-atas', -18, -10, 30, 0, TRUE, 'geser-kiri', 200, 1300, 'melayang', 7, FALSE, FALSE, 85, 60),
    ('wor-biak', 'galeri', '/img/tema/suku/wor-biak-orn-atas.svg', 'tengah-atas', 0, -78, 84, 0, FALSE, 'turun', 200, 1400, 'goyang', 6, FALSE, TRUE, 95, 70),
    ('wor-biak', 'acara', '/img/tema/suku/wor-biak-orn-ikon.svg', 'tengah-atas', 0, -6, 92, 0, FALSE, 'naik', 200, 1600, 'none', 9, FALSE, TRUE, 28, 80),
    ('wor-biak', 'acara', '/img/tema/suku/wor-biak-orn-sudut.svg', 'kanan-bawah', 16, 20, 28, 180, FALSE, 'ayun-kanan', 600, 1300, 'goyang', 8, FALSE, FALSE, 85, 90),
    ('wor-biak', 'rsvp', '/img/tema/suku/wor-biak-orn-ikon.svg', 'tengah-bawah', 0, 12, 80, 0, FALSE, 'naik', 300, 1600, 'none', 9, FALSE, TRUE, 22, 100),
    ('kulit-kayu-sentani', 'sampul', '/img/tema/suku/kulit-kayu-sentani-orn-tokoh.svg', 'kiri-atas', -30, -18, 40, 0, TRUE, 'geser-kiri', 900, 1600, 'melayang', 5, FALSE, TRUE, 100, 10),
    ('kulit-kayu-sentani', 'sampul', '/img/tema/suku/kulit-kayu-sentani-orn-tokoh.svg', 'kanan-atas', 30, -10, 32, 0, FALSE, 'geser-kanan', 1500, 1600, 'melayang', 6, FALSE, TRUE, 100, 20),
    ('kulit-kayu-sentani', 'sampul', '/img/tema/suku/kulit-kayu-sentani-orn-sudut.svg', 'kiri-bawah', -36, 36, 30, 180, TRUE, 'ayun-kiri', 400, 1300, 'goyang', 8, FALSE, TRUE, 85, 30),
    ('kulit-kayu-sentani', 'sampul', '/img/tema/suku/kulit-kayu-sentani-orn-sudut.svg', 'kanan-bawah', 36, 36, 30, 180, FALSE, 'ayun-kanan', 700, 1300, 'goyang', 9, FALSE, TRUE, 85, 40),
    ('kulit-kayu-sentani', 'mempelai', '/img/tema/suku/kulit-kayu-sentani-orn-lambang.svg', 'tengah-atas', 0, -46, 22, 0, FALSE, 'zoom', 300, 1200, 'putar', 36, FALSE, TRUE, 90, 50),
    ('kulit-kayu-sentani', 'kisah', '/img/tema/suku/kulit-kayu-sentani-orn-tokoh.svg', 'kiri-atas', -18, -10, 30, 0, TRUE, 'geser-kiri', 200, 1300, 'melayang', 7, FALSE, FALSE, 85, 60),
    ('kulit-kayu-sentani', 'galeri', '/img/tema/suku/kulit-kayu-sentani-orn-atas.svg', 'tengah-atas', 0, -78, 84, 0, FALSE, 'turun', 200, 1400, 'goyang', 6, FALSE, TRUE, 95, 70),
    ('kulit-kayu-sentani', 'acara', '/img/tema/suku/kulit-kayu-sentani-orn-ikon.svg', 'tengah-atas', 0, -6, 92, 0, FALSE, 'naik', 200, 1600, 'none', 9, FALSE, TRUE, 28, 80),
    ('kulit-kayu-sentani', 'acara', '/img/tema/suku/kulit-kayu-sentani-orn-sudut.svg', 'kanan-bawah', 16, 20, 28, 180, FALSE, 'ayun-kanan', 600, 1300, 'goyang', 8, FALSE, FALSE, 85, 90),
    ('kulit-kayu-sentani', 'rsvp', '/img/tema/suku/kulit-kayu-sentani-orn-ikon.svg', 'tengah-bawah', 0, 12, 80, 0, FALSE, 'naik', 300, 1600, 'none', 9, FALSE, TRUE, 22, 100)
  ) AS a(theme, bagian, img, posisi, x, y, lebar, rotasi, cermin, masuk, jeda, durasi, gerak, kecepatan, depan, hp, opasitas, urutan)
 WHERE EXISTS (SELECT 1 FROM themes t WHERE t.slug = a.theme)
   AND NOT EXISTS (SELECT 1 FROM theme_ornaments o WHERE o.theme = a.theme)
 ORDER BY a.theme, a.urutan;
