# 100 tema undangan adat Nusantara.
# Tiap tema: (nama, label wilayah, deskripsi, tag, primary, gold, bg, gelap?, ubin motif, lambang)
# Konfigurasi rumpun daerah menentukan pilihan huruf, animasi, dan aksen.

REGIONS = {
    "jawa": dict(nuansa="Jawa", accent="#7b2d12", fonts=["cinzel", "cormorant", "marcellus", "playfair"],
                 scripts=["pinyon", "great-vibes", "", "allura"], opens=["gebyok-jawa", "gerbang", "tirai", "gebyok-jawa", "pudar"],
                 floats=["melati-gugur", "kelopak", "melati-gugur", "bintang", "none"], scrolls=["naik", "zoom", "lipat", "pudar"]),
    "sunda": dict(nuansa="Sunda", accent="#1d4e89", fonts=["cormorant", "marcellus", "playfair", "lora"],
                  scripts=["parisienne", "pinyon", "great-vibes", ""], opens=["mega-mendung", "amplop", "tirai", "mega-mendung"],
                  floats=["melati-gugur", "kupu", "kelopak", "melati-gugur"], scrolls=["geser", "naik", "pudar", "zoom"]),
    "minang": dict(nuansa="Minang", accent="#9b1c1c", fonts=["cinzel", "dm-serif", "marcellus", "playfair"],
                   scripts=["great-vibes", "", "pinyon", "alex-brush"], opens=["songket-minang", "gerbang", "songket-minang", "tirai"],
                   floats=["kelopak", "none", "bintang", "daun-sirih"], scrolls=["zoom", "naik", "lipat", "geser"]),
    "batak": dict(nuansa="Batak", accent="#a3201b", fonts=["cinzel", "dm-serif", "marcellus", "lora"],
                  scripts=["", "alex-brush", "great-vibes", ""], opens=["gorga-batak", "gerbang", "gorga-batak", "pudar"],
                  floats=["none", "daun-sirih", "bintang", "none"], scrolls=["geser", "zoom", "naik", "blur"]),
    "melayu": dict(nuansa="Melayu Deli", accent="#c79a1d", fonts=["marcellus", "cormorant", "cinzel", "playfair"],
                   scripts=["great-vibes", "pinyon", "allura", ""], opens=["tirai", "amplop", "gerbang", "tirai"],
                   floats=["daun-sirih", "kelopak", "melati-gugur", "bintang"], scrolls=["naik", "lipat", "geser", "pudar"]),
    "maluku": dict(nuansa="Maluku", accent="#0e5e6f", fonts=["lora", "playfair", "cormorant", "dm-serif"],
                   scripts=["allura", "", "parisienne", "great-vibes"], opens=["tenun-maluku", "pudar", "tenun-maluku", "amplop"],
                   floats=["cengkih-gugur", "kupu", "cengkih-gugur", "bintang"], scrolls=["geser", "naik", "blur", "zoom"]),
    "betawi": dict(nuansa="Betawi", accent="#d35400", fonts=["dm-serif", "playfair", "lora", "marcellus"],
                   scripts=["", "great-vibes", "alex-brush", ""], opens=["amplop", "tirai", "gerbang", "pudar"],
                   floats=["kelopak", "melati-gugur", "kupu", "none"], scrolls=["zoom", "geser", "naik", "naik"]),
    "bali": dict(nuansa="Bali", accent="#2f6b3b", fonts=["marcellus", "cormorant", "cinzel", "lora"],
                 scripts=["parisienne", "pinyon", "", "allura"], opens=["lawang-bali", "pudar", "lawang-bali", "gerbang"],
                 floats=["kamboja-gugur", "kupu", "kamboja-gugur", "kamboja-gugur"], scrolls=["naik", "blur", "pudar", "zoom"]),
    "bugis": dict(nuansa="Bugis-Makassar", accent="#c2185b", fonts=["playfair", "cinzel", "marcellus", "dm-serif"],
                  scripts=["great-vibes", "", "pinyon", ""], opens=["tirai", "gerbang", "amplop", "pudar"],
                  floats=["kelopak", "none", "bintang", "kelopak"], scrolls=["geser", "naik", "zoom", "lipat"]),
    "toraja": dict(nuansa="Toraja", accent="#a31b1b", fonts=["cinzel", "dm-serif", "marcellus"],
                   scripts=["", "alex-brush", ""], opens=["gerbang", "pudar", "tirai"],
                   floats=["none", "bintang", "none"], scrolls=["zoom", "lipat", "naik"]),
    "aceh": dict(nuansa="Aceh", accent="#b8860b", fonts=["cinzel", "marcellus", "playfair", "cormorant"],
                 scripts=["", "great-vibes", "pinyon", ""], opens=["gerbang", "tirai", "amplop", "pudar"],
                 floats=["kelopak", "bintang", "kelopak", "bintang"], scrolls=["naik", "pudar", "zoom", "blur"]),
    "palembang": dict(nuansa="Palembang", accent="#b71c1c", fonts=["cinzel", "playfair", "marcellus", "dm-serif"],
                      scripts=["great-vibes", "", "pinyon", "allura"], opens=["gerbang", "tirai", "pudar", "gerbang"],
                      floats=["bintang", "kelopak", "none", "bintang"], scrolls=["zoom", "naik", "geser", "blur"]),
    "lampung": dict(nuansa="Lampung", accent="#a0161b", fonts=["cinzel", "marcellus", "playfair"],
                    scripts=["", "great-vibes", "pinyon"], opens=["gerbang", "tirai", "amplop"],
                    floats=["bintang", "kelopak", "none"], scrolls=["zoom", "geser", "naik"]),
    "dayak": dict(nuansa="Dayak", accent="#c62828", fonts=["dm-serif", "cinzel", "marcellus"],
                  scripts=["", "alex-brush", ""], opens=["gerbang", "pudar", "tirai"],
                  floats=["bulu-enggang", "bulu-enggang", "none"], scrolls=["geser", "zoom", "lipat"]),
    "papua": dict(nuansa="Papua", accent="#d84315", fonts=["dm-serif", "lora", "marcellus"],
                  scripts=["", "allura", ""], opens=["pudar", "tirai", "pudar"],
                  floats=["kupu", "none", "kupu"], scrolls=["geser", "naik", "blur"]),
    "ntt": dict(nuansa="NTT", accent="#8a2c1d", fonts=["lora", "marcellus", "dm-serif"],
                scripts=["", "alex-brush", "allura"], opens=["tenun-maluku", "tirai", "pudar"],
                floats=["none", "kupu", "bintang"], scrolls=["zoom", "geser", "naik"]),
    "minahasa": dict(nuansa="Minahasa", accent="#1f6f8b", fonts=["playfair", "lora"],
                     scripts=["parisienne", "allura"], opens=["amplop", "pudar"],
                     floats=["kupu", "bintang"], scrolls=["naik", "geser"]),
}

L = False  # terang
D = True   # gelap

THEMES = {
"jawa": [
 ("Kawung Keraton Surakarta", "Keraton Surakarta", "Motif kawung empat kelopak lambang kesucian, gunungan wayang, dan pintu gebyok yang terbuka perlahan ala Kasunanan.", ["Batik Kawung", "Gamelan Pembuka", "Paes Ageng"], "#4a2c17", "#c9a14a", "#fbf6ec", L, "kawung", "gunungan"),
 ("Parang Rusak Ngayogyakarta", "Keraton Yogyakarta", "Garis parang miring yang tak putus — doa agar rumah tangga tegar melawan rintangan, dalam sogan cokelat keraton.", ["Batik Parang", "Basahan", "QR Check-In"], "#5b3416", "#c49a3c", "#f8f1e5", L, "parang", "gunungan"),
 ("Truntum Tresna Sejati", "Solo Basahan", "Bintang-bintang truntum melambangkan cinta yang tumbuh kembali, dipakai orang tua saat ijab kabul putra-putrinya.", ["Batik Truntum", "Kisah Cinta", "Musik Gending"], "#2f2a4a", "#c6a15b", "#f7f4ee", L, "truntum", "gunungan"),
 ("Sidomukti Prada Emas", "Paes Ageng", "Sidomukti berlapis prada emas: harapan hidup mulia, cukup, dan bahagia bagi kedua mempelai.", ["Prada Emas", "Batik Sidomukti", "Amplop Digital"], "#3d1f12", "#d4a83a", "#fcf5e6", L, "sidomukti", "gunungan"),
 ("Sekar Jagad Nusantara", "Batik Sekar Jagad", "Peta bunga sedunia dalam satu kain — merayakan dua keluarga yang dipersatukan dalam keberagaman.", ["Sekar Jagad", "Galeri Foto", "RSVP Sesi"], "#264d3b", "#c9a54e", "#f4f8f1", L, "bunga-tabur", "gunungan"),
 ("Gunungan Wayang Kulit", "Pagelaran Wayang", "Gunungan kayon sebagai pembuka lakon kehidupan baru, diiringi siluet wayang dan nuansa kelir malam.", ["Siluet Wayang", "Mode Gelap", "Gamelan"], "#e3c27a", "#e3c27a", "#16120c", D, "parang", "gunungan"),
 ("Gebyok Kudus Ukir", "Kudus Kota Kretek", "Ukiran gebyok kayu jati Kudus yang megah, membuka undangan seperti pintu rumah adat pesisir utara.", ["Ukir Jati", "Pintu Gebyok", "Love Story"], "#5a3a1e", "#b8892f", "#f6efe3", L, "sidomukti", "gunungan"),
 ("Lurik Jogja Sederhana", "Lurik Klaten", "Garis lurik tenun Klaten yang bersahaja — untuk pasangan yang menyukai kesederhanaan nan hangat.", ["Tenun Lurik", "Minimalis", "Intimate Wedding"], "#3b4a3a", "#b08d57", "#f6f5ef", L, "lurik", "gunungan"),
 ("Kembang Setaman Siraman", "Siraman Jawa", "Taburan kembang setaman mawar, melati, dan kantil dari prosesi siraman yang wangi dan suci.", ["Kembang Setaman", "Siraman", "Melati Berguguran"], "#6b3a4a", "#c9a76a", "#fcf4f3", L, "bunga-tabur", "gunungan"),
 ("Pendopo Joglo Agung", "Rumah Joglo", "Atap joglo bertumpang dan saka guru — undangan selapang pendopo untuk menyambut seluruh sanak saudara.", ["Arsitektur Joglo", "Peta Lokasi", "Buku Tamu"], "#41301f", "#bf9442", "#f7f2e8", L, "kawung", "gunungan"),
 ("Sogan Solo Klasik", "Batik Sogan", "Warna sogan cokelat-kekuningan khas batik Solo, tenang dan berwibawa untuk akad yang khidmat.", ["Warna Sogan", "Akad Khidmat", "QR Check-In"], "#6a4022", "#c39b55", "#fbf3e8", L, "parang", "gunungan"),
 ("Parang Barong Midodareni", "Malam Midodareni", "Parang barong — motif para raja — dalam beludru hitam dan emas untuk malam midodareni yang sakral.", ["Mode Gelap", "Parang Barong", "Foil Emas"], "#e6c06a", "#e6c06a", "#120f0b", D, "parang", "gunungan"),
 ("Kawung Picis Modern", "Jawa Modern", "Kawung picis disederhanakan menjadi geometri modern — adat Jawa untuk pasangan urban.", ["Modern Adat", "Minimalis", "Galeri Foto"], "#1f3b4d", "#c8a35b", "#f3f6f8", L, "kawung", "gunungan"),
 ("Surya Majapahit Trowulan", "Jawa Timur", "Lambang Surya Majapahit bersinar delapan penjuru, terakota bata merah Trowulan yang hangat.", ["Surya Majapahit", "Terakota", "Kisah Cinta"], "#7a3418", "#d09a3e", "#fbf1e8", L, "truntum", "gunungan"),
 ("Batik Pesisir Lasem", "Pesisir Lasem", "Merah bang-bangan Lasem berpadu motif peranakan — perpaduan budaya pesisir yang meriah.", ["Merah Lasem", "Peranakan", "Amplop Digital"], "#8e1f24", "#c99a3f", "#fdf3f0", L, "bunga-tabur", "gunungan"),
 ("Gajah Oling Banyuwangi", "Osing Banyuwangi", "Motif gajah oling suku Osing yang meliuk seperti tanda tanya — pengingat akan Sang Pencipta.", ["Batik Osing", "Gandrung", "RSVP Sesi"], "#23402f", "#c4a24f", "#f3f7f0", L, "kaluak-paku", "gunungan"),
],
"sunda": [
 ("Mega Mendung Cirebon", "Keraton Cirebon", "Awan mega mendung bergradasi biru — kesabaran yang meneduhkan, khas batik Trusmi Cirebon.", ["Mega Mendung", "Batik Trusmi", "Animasi Awan"], "#1c3f6e", "#c9a35a", "#f2f6fb", L, "mega-mendung", "kujang"),
 ("Kujang Pajajaran", "Pakuan Pajajaran", "Sepasang kujang pusaka Pajajaran menjaga ikrar suci — gagah, wibawa, dan berakar sejarah Sunda.", ["Pusaka Kujang", "Adat Sunda", "QR Check-In"], "#2b3f2a", "#c39a45", "#f5f7f0", L, "kujang", "kujang"),
 ("Siger Mojang Priangan", "Mojang Priangan", "Siger emas pengantin Sunda dan untaian melati panjang, anggun seperti mojang Priangan.", ["Siger Sunda", "Melati", "Love Story"], "#5a2342", "#d0a95c", "#fcf4f7", L, "bunga-tabur", "kujang"),
 ("Saweran Melati Priangan", "Upacara Sawer", "Hujan sawer beras kuning, koin, dan melati — doa rezeki melimpah bagi pengantin baru.", ["Upacara Sawer", "Melati Berguguran", "Musik Kecapi"], "#4f3a1c", "#d4ad4c", "#fcf7ea", L, "bunga-tabur", "kujang"),
 ("Angklung Saung Bambu", "Saung Lembur", "Saung bambu dan alunan angklung di tengah sawah — hangat, sederhana, dan penuh keakraban.", ["Bambu", "Rustic", "Intimate Wedding"], "#3e5a2b", "#b8973f", "#f4f8ee", L, "bambu", "kujang"),
 ("Batik Garutan Lembut", "Batik Garut", "Warna gumading lembut batik Garutan dengan bunga-bunga kecil yang manis dan feminin.", ["Batik Garutan", "Pastel", "Galeri Foto"], "#6d4b5f", "#c8a86a", "#fbf6f3", L, "bunga-tabur", "kujang"),
 ("Ngeuyeuk Seureuh", "Adat Ngeuyeuk", "Daun sirih bertemu urat — simbol dua insan yang saling melengkapi dalam prosesi ngeuyeuk seureuh.", ["Daun Sirih", "Prosesi Adat", "RSVP Sesi"], "#2e5236", "#c6a24e", "#f2f8f2", L, "bambu", "kujang"),
 ("Lingkung Gunung Parahyangan", "Parahyangan", "Siluet pegunungan Parahyangan berselimut kabut pagi, sejuk dan tenteram.", ["Pegunungan", "Kabut Pagi", "Peta Lokasi"], "#244a5a", "#bfa063", "#eff6f7", L, "mega-mendung", "kujang"),
 ("Mojang Jajaka Modern", "Sunda Modern", "Kujang dan mega mendung dalam garis modern — untuk mojang jajaka masa kini.", ["Modern Adat", "Editorial", "Amplop Digital"], "#173b52", "#d1aa5c", "#f4f6f8", L, "mega-mendung", "kujang"),
 ("Kebun Teh Ciwidey", "Kebun Teh Ciwidey", "Hamparan kebun teh hijau dan embun pagi Ciwidey — segar untuk pernikahan outdoor.", ["Botanical", "Outdoor", "Kupu-kupu"], "#2f5a34", "#bfa253", "#f1f8ef", L, "bambu", "kujang"),
],
"minang": [
 ("Rumah Gadang Bagonjong", "Ranah Minang", "Atap bagonjong yang menjulang seperti tanduk kerbau — kebanggaan Ranah Minang dalam merah dan emas.", ["Rumah Gadang", "Songket", "Pantun Adat"], "#7a1414", "#d1a23a", "#fdf4ef", L, "pucuk-rebung", "gonjong"),
 ("Songket Pandai Sikek", "Pandai Sikek", "Tenun songket Pandai Sikek berbenang emas — rumit, mewah, dan diwariskan turun-temurun.", ["Songket Emas", "Mewah", "QR Check-In"], "#5e0f17", "#d9ad3f", "#fcf3ec", L, "songket-lepus", "gonjong"),
 ("Suntiang Anak Daro", "Baralek Gadang", "Suntiang emas bertingkat di kepala anak daro — kemegahan baralek gadang yang tak terlupakan.", ["Suntiang", "Baralek", "Galeri Foto"], "#8a1c1c", "#e0b54a", "#fff6ee", L, "pucuk-rebung", "gonjong"),
 ("Pucuak Rabuang Emas", "Agam", "Pucuk rebung — tunas bambu yang tumbuh lurus — doa agar keluarga baru berguna sejak muda.", ["Pucuk Rebung", "Songket", "Love Story"], "#6a1d0f", "#cf9f39", "#fbf2e9", L, "pucuk-rebung", "gonjong"),
 ("Itiak Pulang Patang", "Tanah Datar", "Barisan itik pulang petang yang rapi — teladan kekompakan dan keteraturan dalam rumah tangga.", ["Ukiran Minang", "Keluarga", "RSVP Sesi"], "#3d2a1a", "#c6993d", "#f8f2ea", L, "itiak", "gonjong"),
 ("Kaluak Paku Kacang Balimbiang", "Payakumbuh", "Ukiran kaluak paku — pakis yang melingkar ke dalam — pesan untuk selalu introspeksi diri.", ["Ukiran Pakis", "Filosofi Adat", "Amplop Digital"], "#2c4a2f", "#c9a046", "#f4f7ef", L, "kaluak-paku", "gonjong"),
 ("Marawa Tigo Warna", "Luhak Nan Tigo", "Hitam, merah, dan kuning marawa — tiga luhak Minangkabau berkibar menyambut tamu.", ["Marawa", "Warna Adat", "Peta Lokasi"], "#1a1a1a", "#e3b23c", "#fbf6ea", L, "itiak", "gonjong"),
 ("Jam Gadang Bukittinggi", "Bukittinggi", "Jam Gadang dan Ngarai Sianok — kenangan manis di kota sejuk Bukittinggi.", ["Ikon Kota", "Sejuk", "Kisah Cinta"], "#23463d", "#c8a252", "#f2f7f4", L, "pucuk-rebung", "gonjong"),
 ("Malam Bainai", "Malam Bainai", "Inai merah di jemari anak daro pada malam bainai — hangat, khidmat, dan bercahaya lilin.", ["Mode Gelap", "Malam Bainai", "Foil Emas"], "#e2b04f", "#e2b04f", "#1a0d0d", D, "songket-lepus", "gonjong"),
 ("Pesisir Padang Bundo", "Kota Padang", "Ombak pantai Padang dan songket pesisir — kampung halaman yang selalu dirindukan perantau.", ["Pesisir", "Perantau", "Musik Saluang"], "#7c2a14", "#d3a443", "#fdf5ee", L, "ombak", "gonjong"),
],
"batak": [
 ("Gorga Rumah Bolon", "Batak Toba • Samosir", "Ukiran gorga merah-putih-hitam rumah bolon: tiga warna sakral Batak Toba yang penuh makna.", ["Gorga", "Tiga Warna", "Horas!"], "#1e1e1e", "#c9a24a", "#faf6f1", L, "gorga", "bolon"),
 ("Ulos Ragi Hotang", "Ulos Toba", "Ulos Ragi Hotang yang diselimutkan orang tua — ikatan kasih yang kuat seperti rotan.", ["Ulos", "Mangulosi", "QR Check-In"], "#5a1512", "#c79a42", "#fbf3ef", L, "ulos", "bolon"),
 ("Ulos Sadum Ceria", "Ulos Sadum", "Sadum berwarna cerah penuh sukacita — untuk pesta adat yang meriah dan penuh tawa.", ["Ulos Sadum", "Meriah", "Galeri Foto"], "#8c1d3a", "#d6a843", "#fdf4f6", L, "ulos", "bolon"),
 ("Danau Toba Biru", "Tepian Danau Toba", "Biru tenang Danau Toba dan Pulau Samosir — awal perjalanan yang damai seluas danau.", ["Danau Toba", "Outdoor", "Peta Lokasi"], "#163f5c", "#c5a35a", "#f0f6fa", L, "ombak", "bolon"),
 ("Singa-Singa Gorga", "Huta Batak", "Singa-singa penjaga rumah adat dalam gelap dan merah — gagah, berwibawa, dan melindungi.", ["Mode Gelap", "Gorga", "Foil Emas"], "#e0b65a", "#e0b65a", "#140f0f", D, "gorga", "bolon"),
 ("Uis Karo Beka Buluh", "Karo • Berastagi", "Uis beka buluh dan rumah siwaluh jabu — sejuk dan subur seperti dataran tinggi Karo.", ["Uis Karo", "Berastagi", "Love Story"], "#5c1d1a", "#d1a445", "#fbf4ee", L, "ulos", "bolon"),
 ("Rumah Siwaluh Jabu", "Karo • Lingga", "Rumah adat Karo untuk delapan keluarga — kebersamaan besar dalam satu atap.", ["Rumah Adat Karo", "Keluarga Besar", "RSVP Sesi"], "#3a2418", "#c49742", "#f8f1ea", L, "gorga", "bolon"),
 ("Hiou Simalungun", "Simalungun", "Kain hiou dan gotong khas Simalungun — santun, rapi, dan penuh rasa hormat.", ["Hiou", "Simalungun", "Amplop Digital"], "#4a1e2c", "#c8a04e", "#fbf5f6", L, "ulos", "bolon"),
 ("Gordang Sambilan Mandailing", "Mandailing Natal", "Dentum sembilan gendang gordang sambilan menyambut raja dan ratu sehari dari Mandailing.", ["Gordang Sambilan", "Mandailing", "Musik Adat"], "#2b3d2c", "#c9a24c", "#f4f7f1", L, "gorga", "bolon"),
 ("Horas Medan Modern", "Batak Modern • Medan", "Gorga disederhanakan menjadi garis modern — adat Batak untuk pasangan urban Medan.", ["Modern Adat", "Medan", "Editorial"], "#2a1f1f", "#d0a64e", "#f6f3f2", L, "ulos", "bolon"),
],
"melayu": [
 ("Istana Maimun Kuning", "Istana Maimun • Medan", "Kuning diraja dan lengkung Istana Maimun — kemegahan Kesultanan Deli di jantung Kota Medan.", ["Kuning Diraja", "Istana", "QR Check-In"], "#5c3d0b", "#d9b03d", "#fdf8e8", L, "awan-larat", "masjid"),
 ("Pucuk Rebung Deli", "Melayu Deli", "Pucuk rebung songket Melayu Deli — harapan tumbuh lurus dan berguna bagi sesama.", ["Pucuk Rebung", "Songket", "Love Story"], "#2c4a2a", "#cfa743", "#f5f8ee", L, "pucuk-rebung", "rebung"),
 ("Tepak Sirih Bertabur", "Adat Melayu", "Tepak sirih pembuka kata — adab Melayu menyambut tamu dengan hormat dan senyum.", ["Tepak Sirih", "Pantun", "Amplop Digital"], "#6b2a1a", "#cfa149", "#fcf5ee", L, "bunga-tabur", "rebung"),
 ("Awan Larat Serdang", "Serdang Bedagai", "Ukiran awan larat yang meliuk tanpa putus — rezeki yang mengalir terus bagi keluarga baru.", ["Awan Larat", "Ukiran Melayu", "Galeri Foto"], "#1f4a4a", "#c9a650", "#f0f7f6", L, "awan-larat", "rebung"),
 ("Songket Batubara", "Batubara", "Songket Batubara berbenang emas dalam ungu bangsawan — anggun, berkelas, tak lekang waktu.", ["Songket Emas", "Ungu Bangsawan", "RSVP Sesi"], "#432257", "#d4ad4f", "#f8f4fb", L, "songket-lepus", "rebung"),
 ("Masjid Raya Al-Mashun", "Medan Kota", "Kubah dan lengkung Masjid Raya Al-Mashun — nuansa islami yang teduh untuk akad nikah.", ["Islami", "Akad Nikah", "Ayat Ar-Rum"], "#1b4332", "#cfa94f", "#f2f8f4", L, "awan-larat", "masjid"),
],
"maluku": [
 ("Cengkih Pala Banda", "Banda Naira", "Cengkih dan pala, rempah termasyhur dari Banda — harum dan berharga seperti cinta kalian.", ["Rempah", "Cengkih Berguguran", "Kisah Cinta"], "#5a2a14", "#c99a3f", "#fcf5ec", L, "cengkih", "tifa"),
 ("Tifa Totobuang Ambon", "Kota Ambon", "Irama tifa dan totobuang Ambon — semangat sukacita dan persaudaraan orang basudara.", ["Tifa", "Musik Ambon", "QR Check-In"], "#7a1e1e", "#d0a149", "#fdf4ef", L, "tenun", "tifa"),
 ("Pantai Ora Biru", "Seram Utara", "Air sebening kaca dan biru Pantai Ora — pernikahan bernuansa laut timur yang memesona.", ["Pantai", "Biru Laut", "Outdoor"], "#0f4c5c", "#c8a85e", "#eef7f8", L, "ombak", "tifa"),
 ("Tenun Tanimbar", "Kepulauan Tanimbar", "Tenun ikat Tanimbar bermotif tegas — karya tangan perempuan Maluku Tenggara yang memikat.", ["Tenun Ikat", "Kerajinan", "Galeri Foto"], "#3b1f1a", "#c69a48", "#f9f2ec", L, "tenun", "tifa"),
 ("Baileo Negeri", "Negeri Adat", "Baileo — rumah adat tempat musyawarah negeri — simbol restu dan kebersamaan seluruh soa.", ["Rumah Baileo", "Adat Negeri", "RSVP Sesi"], "#2c3b28", "#c6a04a", "#f5f7f0", L, "tenun", "tifa"),
 ("Kesultanan Ternate", "Ternate", "Kemegahan Kesultanan Ternate di kaki Gamalama — kuning emas dan hijau rempah.", ["Kesultanan", "Kuning Emas", "Amplop Digital"], "#4b3a0c", "#d9b13e", "#fcf8e6", L, "cengkih", "tifa"),
 ("Pela Gandong", "Maluku Tengah", "Ikatan pela gandong yang abadi — persaudaraan lintas negeri, kini mempersatukan dua keluarga.", ["Pela Gandong", "Persaudaraan", "Love Story"], "#1d3d5a", "#c7a359", "#f1f5f9", L, "ombak", "tifa"),
 ("Mutiara Kei", "Kepulauan Kei", "Pasir putih terhalus dan kilau mutiara Kei — elegan dalam nuansa malam laut timur.", ["Mode Gelap", "Mutiara", "Bintang Laut"], "#e8cf9a", "#e8cf9a", "#0c1a24", D, "ombak", "tifa"),
],
"betawi": [
 ("Gigi Balang Ondel-Ondel", "Betawi Asli", "Lisplang gigi balang dan ondel-ondel — meriah dan jenaka khas pesta kawinan Betawi.", ["Gigi Balang", "Ondel-Ondel", "Meriah"], "#a63a14", "#d9a73e", "#fff6ec", L, "gigi-balang", "rumoh"),
 ("Kembang Kelapa Palang Pintu", "Palang Pintu", "Kembang kelapa dan tradisi palang pintu: pantun berbalas dan silat sebelum mempelai masuk.", ["Palang Pintu", "Pantun", "QR Check-In"], "#1f5a3a", "#d0a648", "#f1f9f3", L, "kembang-kelapa", "rumoh"),
 ("Rumah Kebaya Condet", "Condet", "Rumah kebaya beratap pelana dan teras luas — ramah menyambut sanak saudara yang datang.", ["Rumah Kebaya", "Keluarga", "Love Story"], "#5a3a1a", "#c69a44", "#fbf4ea", L, "gigi-balang", "rumoh"),
 ("Batik Betawi Tumpal", "Jakarta", "Batik Betawi bermotif tumpal dan warna terang — Jakarta tempo dulu yang ceria.", ["Batik Tumpal", "Ceria", "Galeri Foto"], "#0f5e6b", "#e0a93c", "#effafb", L, "pucuk-rebung", "rumoh"),
 ("Tanjidor Pesisir", "Marunda", "Alunan tanjidor dan angin pesisir Marunda — pesta kawinan Betawi yang hangat dan merakyat.", ["Tanjidor", "Pesisir", "RSVP Sesi"], "#7b2a3a", "#d3a54a", "#fdf3f5", L, "kembang-kelapa", "rumoh"),
],
"bali": [
 ("Candi Bentar Pura", "Gianyar", "Gerbang candi bentar yang terbelah — memasuki babak suci kehidupan berumah tangga.", ["Candi Bentar", "Gerbang Pura", "Kamboja"], "#3b2a1a", "#c9a24b", "#f8f3ea", L, "patra", "candi"),
 ("Kamboja Pura Taman", "Ubud", "Bunga kamboja berguguran di taman pura Ubud — tenang, harum, dan penuh doa.", ["Kamboja Berguguran", "Taman", "Love Story"], "#2f5a3e", "#cba653", "#f2f8f2", L, "kamboja", "candi"),
 ("Patra Punggel Prada", "Klungkung", "Ukiran patra punggel berlapis prada Klungkung — kemewahan seni ukir Bali yang rumit.", ["Patra Punggel", "Prada Emas", "QR Check-In"], "#5a1a1a", "#d6a93f", "#fcf3ee", L, "patra", "candi"),
 ("Payas Agung", "Payas Agung", "Busana payas agung dengan mahkota bunga emas — kemegahan pengantin Bali dalam malam gemerlap.", ["Mode Gelap", "Payas Agung", "Foil Emas"], "#e4bf6a", "#e4bf6a", "#161009", D, "patra", "candi"),
 ("Jatiluwih Subak", "Tabanan", "Terasering sawah Jatiluwih dan sistem subak — harmoni manusia, alam, dan Sang Pencipta.", ["Tri Hita Karana", "Sawah", "Outdoor"], "#2c5a2a", "#c3a04b", "#f2f8ef", L, "kamboja", "candi"),
],
"bugis": [
 ("Phinisi Layar Tujuh", "Bulukumba", "Kapal phinisi berlayar tujuh — bahtera rumah tangga yang tangguh mengarungi samudra.", ["Phinisi", "Bahari", "Kisah Cinta"], "#14365a", "#cfa755", "#f0f5fa", L, "ombak", "phinisi"),
 ("Lipa Sabbe Sengkang", "Sengkang • Wajo", "Sarung sutra lipa sabbe kotak-kotak dari Sengkang — halus berkilau seperti doa kedua keluarga.", ["Sutra Bugis", "Lipa Sabbe", "QR Check-In"], "#6b1a3a", "#d1a74d", "#fdf3f7", L, "balo-renni", "phinisi"),
 ("Baju Bodo Merah Muda", "Bugis", "Baju bodo transparan merah muda — busana tertua Nusantara yang anggun dan bersahaja.", ["Baju Bodo", "Merah Muda", "Galeri Foto"], "#8a2350", "#d4ab5a", "#fdf3f7", L, "balo-renni", "phinisi"),
 ("Balla Lompoa Gowa", "Gowa", "Istana kayu Balla Lompoa Kerajaan Gowa — wibawa raja-raja Makassar dalam cokelat dan emas.", ["Istana Kayu", "Kerajaan Gowa", "Peta Lokasi"], "#4a2c14", "#c99b3f", "#faf2e8", L, "balo-renni", "panggung"),
 ("Malam Mappacci", "Malam Mappacci", "Daun pacci dan lilin pada malam mappacci — penyucian diri sebelum hari bahagia.", ["Mode Gelap", "Mappacci", "Lilin"], "#e2b862", "#e2b862", "#150c12", D, "balo-renni", "phinisi"),
],
"toraja": [
 ("Tongkonan Pa'tedong", "Tana Toraja", "Atap tongkonan berbentuk perahu dan ukiran pa'tedong (kerbau) — lambang kemakmuran keluarga.", ["Tongkonan", "Ukiran Toraja", "Mode Gelap"], "#e3b85a", "#e3b85a", "#140e0c", D, "pa-tedong", "tongkonan"),
 ("Pa'barre Allo", "Rantepao", "Ukiran pa'barre allo — matahari bersinar — doa agar kehidupan baru selalu terang.", ["Pa'barre Allo", "Matahari", "QR Check-In"], "#6e1414", "#d4a640", "#fcf4ec", L, "pa-barre", "tongkonan"),
 ("Kandaure Manik", "Toraja Utara", "Hiasan manik kandaure warna-warni — keindahan perhiasan adat perempuan Toraja.", ["Manik-Manik", "Kandaure", "Galeri Foto"], "#2a1a14", "#cf9f45", "#f9f3ec", L, "pa-barre", "tongkonan"),
],
"aceh": [
 ("Pintu Aceh Emas", "Banda Aceh", "Motif pintu Aceh yang rendah — mengajarkan tamu menunduk hormat saat memasuki rumah.", ["Pintu Aceh", "Islami", "QR Check-In"], "#1b4a2a", "#d3a945", "#f2f8f2", L, "pintu-aceh", "rumoh"),
 ("Bungong Jeumpa", "Aceh Besar", "Bunga jeumpa (cempaka) yang harum, dari lagu daerah yang dikenal seluruh Nusantara.", ["Bunga Cempaka", "Lagu Daerah", "Love Story"], "#7a2a14", "#d6ab48", "#fdf6ec", L, "bunga-tabur", "rumoh"),
 ("Pucok Reubong Kasab", "Kasab Aceh", "Sulaman kasab benang emas bermotif pucok reubong — kemewahan pelaminan Aceh.", ["Kasab Emas", "Pelaminan", "Amplop Digital"], "#5a0f14", "#dcb045", "#fcf2ef", L, "pucuk-rebung", "rumoh"),
 ("Rumoh Aceh Malam", "Serambi Mekkah", "Rumoh Aceh di bawah langit malam Serambi Mekkah — khidmat, islami, dan bercahaya.", ["Mode Gelap", "Islami", "Bintang"], "#e0bb64", "#e0bb64", "#0d1410", D, "pintu-aceh", "rumoh"),
],
"palembang": [
 ("Songket Lepus Emas", "Palembang Darussalam", "Songket lepus yang hampir seluruhnya benang emas — mahkota tenun Palembang Darussalam.", ["Songket Lepus", "Benang Emas", "QR Check-In"], "#6e0f14", "#ddb043", "#fdf3ee", L, "songket-lepus", "limas"),
 ("Aesan Gede", "Kesultanan Palembang", "Busana aesan gede bermahkota emas — kemegahan bangsawan Kesultanan Palembang.", ["Aesan Gede", "Mode Gelap", "Foil Emas"], "#e4be5c", "#e4be5c", "#170b0b", D, "songket-lepus", "limas"),
 ("Rumah Limas Musi", "Tepian Musi", "Rumah limas bertingkat di tepian Sungai Musi — keteduhan keluarga besar yang berjenjang.", ["Rumah Limas", "Sungai Musi", "Love Story"], "#4a2410", "#c99a3c", "#fbf3ea", L, "ombak", "limas"),
 ("Jembatan Ampera Senja", "Palembang Modern", "Ampera bermandikan senja jingga — kenangan romantis kota pempek untuk pasangan modern.", ["Senja", "Modern Adat", "Galeri Foto"], "#8a2a14", "#d9a64a", "#fdf5ef", L, "songket-lepus", "limas"),
],
"lampung": [
 ("Siger Saibatin", "Lampung Pesisir", "Siger emas berlekuk sembilan — mahkota pengantin Lampung dan lambang keagungan perempuan.", ["Siger Lampung", "Foil Emas", "QR Check-In"], "#6a0f14", "#dcb042", "#fdf4ee", L, "tapis-kapal", "siger"),
 ("Tapis Kapal", "Tapis Lampung", "Kain tapis bersulam motif kapal — perjalanan hidup baru yang membawa harapan.", ["Kain Tapis", "Motif Kapal", "Love Story"], "#3a1f12", "#cf9f3e", "#f9f2ea", L, "tapis-kapal", "siger"),
 ("Nuwo Sesat Pepadun", "Lampung Pepadun", "Balai adat nuwo sesat tempat begawi — kemuliaan adat Pepadun dalam malam keemasan.", ["Mode Gelap", "Pepadun", "Siger"], "#e2bb5c", "#e2bb5c", "#140c0a", D, "tapis-kapal", "siger"),
],
"dayak": [
 ("Burung Enggang Borneo", "Kalimantan Tengah", "Enggang gading, burung suci Dayak — kesetiaan seumur hidup pada satu pasangan.", ["Burung Enggang", "Mode Gelap", "Bulu Enggang"], "#e8c066", "#e8c066", "#0f0d0b", D, "dayak", "enggang"),
 ("Aso Naga Manik", "Dayak Kenyah", "Motif aso naga dan manik-manik warna-warni — perlindungan dan kemakmuran rumah tangga.", ["Motif Aso", "Manik Dayak", "QR Check-In"], "#1d1a17", "#d4a43f", "#f8f4ee", L, "dayak", "enggang"),
 ("Rumah Betang Panjang", "Kalimantan Barat", "Rumah betang yang memanjang menampung banyak keluarga — kebersamaan khas Borneo.", ["Rumah Betang", "Keluarga Besar", "Love Story"], "#3c2a14", "#c79a3d", "#f8f2e8", L, "dayak", "enggang"),
],
"papua": [
 ("Cenderawasih Surga", "Tanah Papua", "Bulu cenderawasih, burung dari surga — keindahan tiada tara dari ufuk timur Indonesia.", ["Cenderawasih", "Mode Gelap", "Kupu-kupu"], "#e6bc5a", "#e6bc5a", "#0c120d", D, "asmat", "cenderawasih"),
 ("Ukir Asmat", "Agats • Asmat", "Ukiran kayu Asmat yang tegas dan bermakna — penghormatan pada leluhur dan alam.", ["Ukiran Asmat", "Kayu", "Galeri Foto"], "#4a2410", "#cf9b3c", "#faf2e8", L, "asmat", "cenderawasih"),
 ("Raja Ampat Biru", "Raja Ampat", "Gugusan pulau karst dan laut biru Raja Ampat — pernikahan seindah surga bawah laut.", ["Raja Ampat", "Biru Laut", "Outdoor"], "#0b4d63", "#c8a85a", "#edf7f9", L, "ombak", "cenderawasih"),
],
"ntt": [
 ("Ikat Sumba Kuda", "Sumba Timur", "Tenun ikat Sumba bermotif kuda dan belah ketupat — kekuatan dan kesetiaan dari padang sabana.", ["Tenun Ikat", "Sumba", "QR Check-In"], "#2a1a2e", "#c99742", "#f8f3f6", L, "ikat-sumba", "ikat"),
 ("Tenun Sikka", "Flores • Sikka", "Tenun Sikka berwarna tanah dari pewarna alam — hangat, tulus, dan dibuat dengan sabar.", ["Pewarna Alam", "Flores", "Love Story"], "#5a2414", "#c9963d", "#fbf2ea", L, "ikat-sumba", "ikat"),
 ("Sasando Rote", "Pulau Rote", "Petikan sasando dari daun lontar Pulau Rote — melodi lembut untuk hari bahagia.", ["Sasando", "Musik Tradisi", "Galeri Foto"], "#1f3d4a", "#c6a35a", "#f0f6f7", L, "tenun", "ikat"),
],
"minahasa": [
 ("Rumah Panggung Woloan", "Tomohon", "Rumah panggung kayu Woloan dan bunga-bunga Tomohon — kota bunga di kaki gunung.", ["Rumah Panggung", "Kota Bunga", "Kupu-kupu"], "#2f4a2a", "#c7a24c", "#f3f8f0", L, "bunga-tabur", "panggung"),
 ("Bunaken Laut Teduh", "Manado", "Taman laut Bunaken yang teduh dan jernih — untuk pasangan yang mencintai lautan.", ["Bunaken", "Biru Laut", "Outdoor"], "#0d4a6b", "#c9a75c", "#eef6fa", L, "ombak", "panggung"),
],
}

# Animasi khas daerah (tabel animations). Gambar dibangkitkan build.py.
ANIM_OPEN = {
    # slug: (nama, warna panel {primary, gold, bg, card, ink, accent}, ubin, lambang, spek tambahan)
    "gebyok-jawa": ("Pintu Gebyok Jawa", dict(primary="#4a2c17", gold="#d0a64a", bg="#f6ecd9", card="#fbf3e3", ink="#2a180c", accent="#7b2d12"), "sidomukti", "gunungan",
                    dict(split="lr", move_pct=0, rotate=100, duration_ms=1500, delay_ms=300, easing="tegas", content_exit="pudar", orn_effect="membesar", orn_size=120)),
    "mega-mendung": ("Tirai Mega Mendung", dict(primary="#1c3f6e", gold="#d6b066", bg="#eef4fb", card="#f6f9fd", ink="#0e2240", accent="#2b6cb0"), "mega-mendung", "kujang",
                     dict(split="lr", move_pct=104, rotate=0, duration_ms=1300, delay_ms=250, easing="lembut", content_exit="naik", orn_effect="berputar", orn_size=90)),
    "songket-minang": ("Songket Minang Terangkat", dict(primary="#6e0f14", gold="#ddb043", bg="#fbeee6", card="#fff6ef", ink="#2a0a0a", accent="#9b1c1c"), "songket-lepus", "gonjong",
                       dict(split="tb", move_pct=103, rotate=0, duration_ms=1300, delay_ms=250, easing="tegas", content_exit="mengecil", orn_effect="membesar", orn_size=130)),
    "gorga-batak": ("Pintu Gorga Batak", dict(primary="#1c1a19", gold="#d2a64c", bg="#f6efe8", card="#fbf6f1", ink="#151312", accent="#a3201b"), "gorga", "bolon",
                    dict(split="lr", move_pct=0, rotate=105, duration_ms=1400, delay_ms=300, easing="tegas", content_exit="pudar", orn_effect="membesar", orn_size=130)),
    "tenun-maluku": ("Tenun Terangkat", dict(primary="#3b1f1a", gold="#d2a24c", bg="#f6ece4", card="#fbf4ee", ink="#1e0f0c", accent="#8a2c1d"), "tenun", "tifa",
                     dict(split="full", move_pct=105, rotate=0, duration_ms=1400, delay_ms=200, easing="lembut", content_exit="naik", orn_effect="jatuh", orn_size=100)),
    "lawang-bali": ("Lawang Candi Bentar", dict(primary="#3b2a1a", gold="#d1aa50", bg="#f5ede0", card="#fbf6ee", ink="#1d140b", accent="#2f6b3b"), "patra", "candi",
                    dict(split="lr", move_pct=101, rotate=0, scale=112, fade=True, duration_ms=1300, delay_ms=250, easing="lembut", content_exit="membesar", orn_effect="membesar", orn_size=110)),
}

ANIM_FLOAT = {
    "melati-gugur": ("Melati Berguguran", "melati", dict(float_motion="jatuh", float_size=16, float_speed=13, float_count=10)),
    "kamboja-gugur": ("Kamboja Berguguran", "kamboja", dict(float_motion="jatuh", float_size=22, float_speed=15, float_count=8)),
    "cengkih-gugur": ("Cengkih Berguguran", "cengkih", dict(float_motion="jatuh", float_size=12, float_speed=12, float_count=10)),
    "bulu-enggang": ("Bulu Enggang Melayang", "bulu-enggang", dict(float_motion="naik", float_size=20, float_speed=16, float_count=7)),
    "daun-sirih": ("Daun Sirih Berguguran", "daun-sirih", dict(float_motion="jatuh", float_size=18, float_speed=14, float_count=8)),
}
