# 38 tema undangan — satu per PROVINSI Indonesia (dibaca build.py; nama berkas
# bukan data.py agar tak bentrok dengan scripts/nusantara/data.py saat diimpor).
#
# Tiap tema dibedakan bukan hanya warna: rumpun ornamen (tokoh pengapit, ikon
# bangunan, hiasan gantung — scripts/ornamen/adat.py), ubin motif kain &
# lambang (scripts/nusantara/motifs.py), animasi BUKA, koreografi GULIR,
# hiasan melayang, tata letak, dan huruf.
#
# Kolom: slug, nama, provinsi (region), nuansa (rumpun budaya untuk filter
# katalog), deskripsi, tag, primary, gold, bg, gelap?, set ornamen, ubin,
# lambang, ikon khusus (None = ikon set), buka, gulir, hiasan, layout, huruf,
# huruf skrip.
#
# `buka`:
#   "khas:<split>"  → animasi pintu BARU khusus tema ini (panel bermotif ubin +
#                     lambang tema dalam warnanya sendiri), varian di VARIAN_BUKA;
#   nama lain       → animasi yang sudah ada (bawaan / 009).

T = True   # gelap
F = False  # terang

PROVINSI = [
 # ── Sumatera ─────────────────────────────────────────────────────────────
 ("aceh-pintu-seulanga", "Pintu Seulanga Aceh", "Aceh", "Aceh",
  "Ukiran pintu Aceh bermotif bunga seulanga, kubah masjid raya, dan lentera — kemegahan Serambi Mekkah dalam hijau-emas.",
  ["Pintu Aceh", "Islami", "Lentera Bergoyang"], "#1f4d2b", "#d4a52c", "#fbf7ec", F, "aceh", "pintu-aceh", "rumoh", None,
  "khas:lr-ayun", "keraton", "kilau-emas", "bingkai", "cinzel", "great-vibes"),
 ("ulos-ragi-hotang", "Ulos Ragi Hotang", "Sumatera Utara", "Batak",
  "Ulos ragi hotang yang diselempangkan sebagai doa restu, rumah bolon bergorga, dan kain gantung merah-hitam Toba.",
  ["Ulos", "Gorga", "Rumah Bolon"], "#8e1b1b", "#c9a24a", "#f8f1ea", F, "batak", "ulos", "bolon", None,
  "gorga-batak", "geser", "kilau-emas", "gerbang", "dm-serif", "alex-brush"),
 ("gonjong-rumah-gadang", "Gonjong Rumah Gadang", "Sumatera Barat", "Minang",
  "Malam baralek di rumah gadang: gonjong runcing bertatah emas, rangkiang, dan marawa berkibar di atas songket hitam.",
  ["Mode Gelap", "Songket", "Baralek"], "#e0b34a", "#e0b34a", "#170c0a", T, "minang", "itiak", "gonjong", None,
  "songket-minang", "tenun", "kilau-emas", "bingkai", "cinzel", "great-vibes"),
 ("selembayung-riau", "Selembayung Melayu Riau", "Riau", "Melayu",
  "Selembayung di puncak rumah Melayu Riau, pucuk rebung kuning diraja, dan payung kebesaran — santun dan berwibawa.",
  ["Pucuk Rebung", "Kuning Diraja", "Payung Kebesaran"], "#2e5a3a", "#e0b532", "#fdf8e6", F, "melayu", "pucuk-rebung", "rebung", None,
  "khas:full-naik", "naik", "daun-sirih", "klasik", "marcellus", "great-vibes"),
 ("lancang-kuning-kepri", "Lancang Kuning Kepulauan Riau", "Kepulauan Riau", "Melayu",
  "Perahu lancang kuning berlayar di antara pulau-pulau Kepri, ombak tenang, dan karang — pernikahan bernuansa bahari Melayu.",
  ["Bahari", "Ombak", "Melayu Pesisir"], "#0f5f6b", "#e3b83a", "#f1f8f7", F, "laut", "pucuk-rebung", "phinisi", "phinisi",
  "khas:lr-geser", "ombak", "kupu", "gerbang", "playfair", "parisienne"),
 ("durian-pecah-jambi", "Batik Durian Pecah Jambi", "Jambi", "Melayu",
  "Batik Jambi bermotif durian pecah dan kaluak paku, rumah panggung kajang lako, dan untaian lentera di tepian Batanghari.",
  ["Batik Jambi", "Rumah Panggung", "Kelopak Berguguran"], "#6d2a1f", "#cf9a3a", "#faf1e7", F, "melayu", "kaluak-paku", "rebung", "rumah_panggung",
  "khas:tb-belah", "lipat", "kelopak", "editorial", "lora", "allura"),
 ("songket-limas-palembang", "Songket Limas Palembang", "Sumatera Selatan", "Palembang",
  "Aesan gede berlapis songket lepus emas, rumah limas berundak, dan payung kebesaran Kesultanan Palembang Darussalam.",
  ["Mode Gelap", "Songket Lepus", "Aesan Gede"], "#e0b24a", "#e0b24a", "#1a0b0b", T, "palembang", "songket-lepus", "limas", None,
  "gerbang", "keraton", "kilau-emas", "bingkai", "cinzel", "great-vibes"),
 ("granit-belitung", "Pesisir Granit Belitung", "Kepulauan Bangka Belitung", "Melayu",
  "Batu granit raksasa, laut biru jernih, dan pasir putih Belitung — undangan teduh untuk pasangan pecinta pantai.",
  ["Pantai", "Laut Biru", "Kupu-kupu"], "#145a7a", "#d9b26a", "#f3f8fb", F, "laut", "ombak", "phinisi", None,
  "tirai", "ombak", "kupu", "klasik", "playfair", "parisienne"),
 ("rafflesia-bengkulu", "Rafflesia Bengkulu", "Bengkulu", "Melayu",
  "Bunga rafflesia raksasa yang mekar langka, rumah bubungan lima, dan kain besurek berhuruf Arab gundul khas Bengkulu.",
  ["Batik Besurek", "Rafflesia", "Mekar"], "#9b2f2f", "#d3a45a", "#fdf3ee", F, "alam", "bunga-tabur", "rebung", "rumah_panggung",
  "khas:full-zoom", "mekar", "kelopak", "klasik", "cormorant", "great-vibes"),
 ("siger-tapis-lampung", "Siger Tapis Lampung", "Lampung", "Lampung",
  "Siger emas bercabang sembilan, kain tapis bersulam benang emas bermotif kapal, dan kain gantung merah-emas.",
  ["Siger", "Tapis", "Kilau Emas"], "#8f1d1d", "#d9ac3a", "#fcf4e9", F, "lampung", "tapis-kapal", "siger", None,
  "khas:tb-naik", "zoom", "kilau-emas", "gerbang", "cinzel", "alex-brush"),
 # ── Jawa ─────────────────────────────────────────────────────────────────
 ("ondel-ondel-betawi", "Ondel-Ondel Betawi", "DKI Jakarta", "Betawi",
  "Sepasang ondel-ondel mengapit, rumah kebaya berlisplang gigi balang, dan meriahnya palang pintu Betawi.",
  ["Palang Pintu", "Gigi Balang", "Ceria"], "#a33b16", "#e0b03c", "#fff6ea", F, "betawi", "gigi-balang", "panggung", None,
  "amplop", "geser", "kelopak", "gerbang", "dm-serif", "great-vibes"),
 ("kujang-pasundan", "Kujang Pasundan", "Jawa Barat", "Sunda",
  "Kujang pusaka, saung bambu di pematang, golek menari, dan mega berarak di langit Parahyangan.",
  ["Kujang", "Saung Bambu", "Wayang Golek"], "#2f5d3a", "#c9a24e", "#f4f8ee", F, "sunda", "bambu", "kujang", None,
  "khas:lr-geser", "anggun", "kupu", "klasik", "cormorant", "parisienne"),
 ("menara-banten", "Menara Masjid Agung Banten", "Banten", "Sunda",
  "Menara Masjid Agung Banten yang bersejarah, lentera Kesultanan, dan batik datulaya — sakral dan khidmat.",
  ["Islami", "Kesultanan Banten", "Lentera"], "#145c55", "#cfa64c", "#f2f8f6", F, "aceh", "sidomukti", "masjid", None,
  "khas:tb-belah", "naik", "bintang", "bingkai", "marcellus", "allura"),
 ("joglo-sidomukti", "Joglo Sidomukti Solo", "Jawa Tengah", "Jawa",
  "Pendopo joglo bersaka guru, batik sidomukti sogan, dan sepasang wayang kulit mengapit — adat Solo yang anggun.",
  ["Batik Sidomukti", "Joglo", "Melati Berguguran"], "#5b3416", "#c99a3c", "#f8efe2", F, "jawa", "sidomukti", "gunungan", None,
  "gebyok-ukir", "keraton", "melati-gugur", "bingkai", "cinzel", "great-vibes"),
 ("parang-keraton-yogya", "Parang Keraton Ngayogyakarta", "DI Yogyakarta", "Jawa",
  "Kelir menyala di malam keraton: gunungan dikebutkan, wayang masuk dari bayangan, dan parang barong berlapis emas.",
  ["Mode Gelap", "Pagelaran Wayang", "Parang Barong"], "#e3c27a", "#e3c27a", "#14100b", T, "jawa", "parang", "gunungan", None,
  "pagelaran-wayang", "bayang", "kunang", "klasik", "cinzel", "great-vibes"),
 ("gapura-majapahit", "Gapura Wringin Lawang Majapahit", "Jawa Timur", "Jawa",
  "Gapura bata merah Wringin Lawang terbelah menyambut tamu, Surya Majapahit bersinar, dan batik truntum terakota.",
  ["Gapura Terbelah", "Terakota", "Surya Majapahit"], "#7a3418", "#d09a3e", "#fbf1e8", F, "jawa", "truntum", "gunungan", "candi_bentar",
  "candi-bentar", "zoom", "bintang", "gerbang", "marcellus", "great-vibes"),
 # ── Bali & Nusa Tenggara ─────────────────────────────────────────────────
 ("penjor-pura-bali", "Penjor Pura Besakih", "Bali", "Bali",
  "Penjor melengkung menghias jalan pura, kain poleng hitam-putih, dan kamboja berguguran di gerbang candi bentar.",
  ["Kain Poleng", "Penjor", "Kamboja Berguguran"], "#1d1d1b", "#c8a248", "#f7f3ea", F, "bali", "patra", "candi", None,
  "lawang-bali", "anggun", "kamboja-gugur", "gerbang", "marcellus", "parisienne"),
 ("tenun-sasak-lombok", "Tenun Sasak Lombok", "Nusa Tenggara Barat", "Sasak",
  "Lumbung padi Sasak beratap ilalang, tenun songket Sukarara yang diurai helai demi helai, dan pohon lontar di pantai Lombok.",
  ["Tenun Sasak", "Lumbung", "Kain Diurai"], "#283c6b", "#d0a14a", "#f4f6fb", F, "ntt", "tenun", "ikat", "rangkiang",
  "tenun-songket", "tenun", "kupu", "bingkai", "lora", "allura"),
 ("ikat-sumba-sasando", "Ikat Sumba & Sasando", "Nusa Tenggara Timur", "NTT",
  "Kain ikat Sumba yang ditenun berbulan-bulan, alunan sasando dari Rote, dan pohon lontar di bawah langit malam Flores.",
  ["Mode Gelap", "Ikat Sumba", "Sasando"], "#d9a95a", "#d9a95a", "#1a120e", T, "ntt", "ikat-sumba", "ikat", None,
  "tenun-maluku", "lipat", "bintang", "bingkai", "lora", "alex-brush"),
 # ── Kalimantan ───────────────────────────────────────────────────────────
 ("radakng-kanayatn", "Rumah Radakng Kanayatn", "Kalimantan Barat", "Dayak",
  "Rumah panjang radakng Dayak Kanayatn, burung enggang terbang mengapit, dan bulu enggang melayang turun.",
  ["Enggang", "Rumah Panjang", "Bulu Melayang"], "#8c1c13", "#e0a93a", "#fbf2e8", F, "dayak", "dayak", "enggang", None,
  "khas:lr-ayun", "geser", "bulu-enggang", "gerbang", "dm-serif", "alex-brush"),
 ("batang-garing-ngaju", "Batang Garing Ngaju", "Kalimantan Tengah", "Dayak",
  "Batang garing — pohon kehidupan Dayak Ngaju — tumbuh di tengah undangan, enggang di dahan, dan daun gugur berputar.",
  ["Pohon Kehidupan", "Enggang", "Daun Gugur"], "#2c5530", "#e2b53a", "#f3f8ee", F, "dayak", "dayak", "enggang", "pohon",
  "taman-daun", "mekar", "daun-gugur", "klasik", "cormorant", "great-vibes"),
 ("sasirangan-banjar", "Sasirangan Banjar", "Kalimantan Selatan", "Banjar",
  "Kain sasirangan ungu bermotif awan berarak, rumah bubungan tinggi, dan pasar terapung di Sungai Martapura.",
  ["Sasirangan", "Bubungan Tinggi", "Pasar Terapung"], "#6a2c70", "#d6a64a", "#f8f2f8", F, "melayu", "awan-larat", "rebung", "istana",
  "khas:full-naik", "naik", "kupu", "editorial", "playfair", "parisienne"),
 ("lamin-kenyah", "Lamin Dayak Kenyah", "Kalimantan Timur", "Dayak",
  "Lamin panjang berukir motif Kenyah emas di malam Mahakam, enggang mengepak, dan kilau manik-manik.",
  ["Mode Gelap", "Ukir Kenyah", "Lamin"], "#e1b24a", "#e1b24a", "#0f1410", T, "dayak", "dayak", "enggang", "betang",
  "gerbang", "keraton", "bulu-enggang", "bingkai", "dm-serif", "great-vibes"),
 ("kayan-tidung", "Sungai Kayan Tidung", "Kalimantan Utara", "Melayu",
  "Istana Bulungan di tepi Sungai Kayan, payung kuning Tidung, dan daun sirih untuk menyambut tamu.",
  ["Istana Bulungan", "Payung Kuning", "Daun Sirih"], "#4a5d23", "#d9b23c", "#f8f8ec", F, "melayu", "pucuk-rebung", "rebung", None,
  "amplop", "geser", "daun-sirih", "gerbang", "marcellus", "allura"),
 # ── Sulawesi ─────────────────────────────────────────────────────────────
 ("walewangko-minahasa", "Rumah Walewangko Minahasa", "Sulawesi Utara", "Minahasa",
  "Rumah panggung walewangko dari Woloan, krisan Tomohon bermekaran, dan kain bentenan — hangat ala Minahasa.",
  ["Krisan Tomohon", "Rumah Panggung", "Kain Bentenan"], "#1f6f8b", "#d2a85a", "#f1f7fa", F, "minahasa", "bunga-tabur", "panggung", None,
  "khas:lr-geser", "naik", "kupu", "klasik", "playfair", "parisienne"),
 ("karawo-gorontalo", "Sulam Karawo Gorontalo", "Gorontalo", "Gorontalo",
  "Sulaman karawo yang diiris benang demi benang, rumah dulohupa, dan untaian bunga — lembut dan penuh kesabaran.",
  ["Sulam Karawo", "Dulohupa", "Kelopak"], "#7a1f4b", "#d6a74a", "#fbf1f5", F, "minahasa", "bunga-tabur", "panggung", None,
  "khas:full-zoom", "lipat", "kelopak", "editorial", "cormorant", "allura"),
 ("souraja-kaili", "Souraja Kaili Donggala", "Sulawesi Tengah", "Kaili",
  "Rumah souraja kaum bangsawan Kaili, tenun Donggala yang diwariskan, dan Teluk Palu yang tenang.",
  ["Tenun Donggala", "Souraja", "Teluk Palu"], "#2d4f5c", "#d1a752", "#f2f6f6", F, "melayu", "tenun", "panggung", "rumah_panggung",
  "khas:tb-naik", "zoom", "bintang", "bingkai", "lora", "great-vibes"),
 ("sandeq-mandar", "Layar Sandeq Mandar", "Sulawesi Barat", "Mandar",
  "Perahu sandeq bercadik melaju dengan layar segitiga, sarung sutra Mandar, dan ombak Selat Makassar.",
  ["Perahu Sandeq", "Sutra Mandar", "Ombak"], "#b0402a", "#d9b04a", "#fdf3ec", F, "bugis", "balo-renni", "phinisi", None,
  "khas:full-naik", "ombak", "kupu", "gerbang", "playfair", "great-vibes"),
 ("tongkonan-toraja", "Tongkonan Toraja", "Sulawesi Selatan", "Toraja",
  "Tongkonan beratap perahu dengan ukiran pa'tedong merah-hitam, tanduk kerbau bersusun — megah di malam Tana Toraja.",
  ["Mode Gelap", "Tongkonan", "Ukir Pa'tedong"], "#e0b04a", "#e0b04a", "#1a1210", T, "toraja", "pa-tedong", "tongkonan", None,
  "khas:lr-ayun", "zoom", "kilau-emas", "bingkai", "cinzel", "alex-brush"),
 ("benteng-buton", "Benteng Keraton Buton", "Sulawesi Tenggara", "Buton",
  "Benteng keraton Buton yang terluas di dunia, istana malige bertingkat, dan tenun Buton bergaris — warisan Kesultanan Wolio.",
  ["Kesultanan Wolio", "Malige", "Tenun Buton"], "#364a2e", "#d1a64b", "#f5f6ee", F, "melayu", "tenun", "masjid", "istana",
  "khas:lr-geser", "anggun", "daun-sirih", "klasik", "marcellus", "great-vibes"),
 # ── Maluku ───────────────────────────────────────────────────────────────
 ("tifa-cengkih-ambon", "Tifa & Cengkih Ambon", "Maluku", "Maluku",
  "Tabuhan tifa, kora-kora membelah laut Banda, dan cengkih berguguran — undangan Ambon manise.",
  ["Tifa", "Kora-Kora", "Cengkih Berguguran"], "#0e5e6f", "#d2a24c", "#eef6f7", F, "maluku", "cengkih", "tifa", None,
  "khas:full-naik", "ombak", "cengkih-gugur", "gerbang", "lora", "allura"),
 ("kedaton-ternate", "Kedaton Ternate", "Maluku Utara", "Maluku",
  "Kedaton Kesultanan Ternate berlatar Gunung Gamalama di malam hari, cengkih emas, dan mahkota bergemerlap.",
  ["Mode Gelap", "Kesultanan Ternate", "Cengkih Emas"], "#d8b25a", "#d8b25a", "#0f1416", T, "maluku", "awan-larat", "tifa", "istana",
  "gerbang", "keraton", "cengkih-gugur", "bingkai", "cinzel", "great-vibes"),
 # ── Papua ────────────────────────────────────────────────────────────────
 ("cendrawasih-papua", "Cendrawasih Tanah Papua", "Papua", "Papua",
  "Cendrawasih terbang mengapit, ukiran Asmat jingga, dan honai — undangan berani nan hangat dari Tanah Papua.",
  ["Cendrawasih", "Ukir Asmat", "Honai"], "#c2410c", "#e1ad3e", "#fff5ea", F, "papua", "asmat", "cenderawasih", None,
  "khas:full-zoom", "geser", "kupu", "gerbang", "dm-serif", "alex-brush"),
 ("raja-ampat", "Laut Biru Raja Ampat", "Papua Barat", "Papua",
  "Gugusan karst Raja Ampat, terumbu karang warna-warni, dan ombak jernih — untuk pasangan yang jatuh cinta pada laut.",
  ["Bahari", "Terumbu Karang", "Ombak"], "#0b5e8a", "#e3b94e", "#eef7fb", F, "laut", "ombak", "cenderawasih", None,
  "tirai", "ombak", "bintang", "klasik", "playfair", "parisienne"),
 ("kaki-seribu-arfak", "Rumah Kaki Seribu Arfak", "Papua Barat Daya", "Papua",
  "Rumah kaki seribu suku Arfak bertiang ratusan, hutan Pegunungan Arfak, dan kawanan burung melintas.",
  ["Rumah Kaki Seribu", "Hutan Arfak", "Burung Melintas"], "#3b5a2a", "#d9a845", "#f4f7ee", F, "papua", "asmat", "cenderawasih", "rumah_panggung",
  "khas:tb-belah", "naik", "burung", "editorial", "lora", "great-vibes"),
 ("ukir-kamoro-mimika", "Ukir Kamoro Mimika", "Papua Tengah", "Papua",
  "Ukiran kayu suku Kamoro dari pesisir Mimika, tifa bertali rotan, dan cendrawasih kuning di hutan bakau.",
  ["Ukir Kamoro", "Tifa", "Kupu-kupu"], "#6b3a1f", "#d8a64a", "#faf2e8", F, "papua", "asmat", "tifa", None,
  "amplop", "zoom", "kupu", "gerbang", "dm-serif", "allura"),
 ("honai-baliem", "Honai Lembah Baliem", "Papua Pegunungan", "Papua",
  "Honai beratap jerami di Lembah Baliem saat malam, api unggun bakar batu, dan kunang-kunang di kaki Jayawijaya.",
  ["Mode Gelap", "Honai", "Lembah Baliem"], "#dcae5a", "#dcae5a", "#13110d", T, "papua", "asmat", "cenderawasih", "honai",
  "khas:lr-ayun", "lipat", "kunang", "bingkai", "dm-serif", "great-vibes"),
 ("asmat-merauke", "Ukir Asmat Merauke", "Papua Selatan", "Papua",
  "Ukiran bis Asmat yang menjulang, rawa biru Merauke, dan rumah semut musamus — Papua Selatan yang luas dan teduh.",
  ["Ukir Asmat", "Rawa Biru", "Daun Gugur"], "#2f4f3a", "#d4a64e", "#f3f6ef", F, "papua", "asmat", "tifa", "pohon",
  "pudar", "zoom", "daun-gugur", "klasik", "cormorant", "alex-brush"),
]

# Varian animasi pintu khas (spek AnimSpec, web/anim.rs) — dipilih lewat
# `khas:<kunci>`. Panel = ubin motif + lambang tema dalam warnanya sendiri.
VARIAN_BUKA = {
    "lr-ayun":  dict(split="lr", move_pct=0, rotate=105, scale=100, fade=False, duration_ms=1500, delay_ms=300, easing="tegas", content_exit="pudar", orn_effect="membesar", orn_size=120),
    "lr-geser": dict(split="lr", move_pct=104, rotate=0, scale=100, fade=False, duration_ms=1300, delay_ms=250, easing="lembut", content_exit="naik", orn_effect="berputar", orn_size=100),
    "tb-belah": dict(split="tb", move_pct=103, rotate=0, scale=100, fade=False, duration_ms=1300, delay_ms=250, easing="tegas", content_exit="mengecil", orn_effect="membesar", orn_size=120),
    "tb-naik":  dict(split="tb", move_pct=105, rotate=0, scale=108, fade=True, duration_ms=1400, delay_ms=200, easing="lembut", content_exit="naik", orn_effect="jatuh", orn_size=110),
    "full-naik": dict(split="full", move_pct=105, rotate=0, scale=100, fade=False, duration_ms=1400, delay_ms=200, easing="lembut", content_exit="naik", orn_effect="jatuh", orn_size=100),
    "full-zoom": dict(split="full", move_pct=0, rotate=0, scale=130, fade=True, duration_ms=1300, delay_ms=250, easing="lembut", content_exit="membesar", orn_effect="membesar", orn_size=120),
}

# Aksen per set ornamen (dipakai palet ornamen bila rumpun tak punya aksen).
AKSEN = {"aceh": "#b8860b", "batak": "#a3201b", "minang": "#9b1c1c", "melayu": "#c79a1d", "laut": "#0e5e6f", "palembang": "#b71c1c",
         "alam": "#2f6b3b", "lampung": "#a0161b", "betawi": "#d35400", "sunda": "#1d4e89", "jawa": "#7b2d12", "bali": "#2f6b3b",
         "ntt": "#8a2c1d", "dayak": "#c62828", "minahasa": "#1f6f8b", "bugis": "#c2185b", "toraja": "#a31b1b", "maluku": "#0e5e6f",
         "papua": "#d84315"}
